//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Mppg.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Unipi.MppgParser.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MppgParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMppgVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MppgParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MppgParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] MppgParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MppgParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] MppgParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMaximum</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMaximum([NotNull] MppgParser.FunctionMaximumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMaxPlusDeconvolution</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMaxPlusDeconvolution([NotNull] MppgParser.FunctionMaxPlusDeconvolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMaxPlusConvolution</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMaxPlusConvolution([NotNull] MppgParser.FunctionMaxPlusConvolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSum</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSum([NotNull] MppgParser.FunctionSumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionBrackets</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBrackets([NotNull] MppgParser.FunctionBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarMultiplicationRight</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarMultiplicationRight([NotNull] MppgParser.FunctionScalarMultiplicationRightContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMinPlusDeconvolution</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMinPlusDeconvolution([NotNull] MppgParser.FunctionMinPlusDeconvolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionUpNonDecreasingClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionUpNonDecreasingClosure([NotNull] MppgParser.FunctionUpNonDecreasingClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSubadditiveClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSubadditiveClosure([NotNull] MppgParser.FunctionSubadditiveClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionConstructorExp</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionConstructorExp([NotNull] MppgParser.FunctionConstructorExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionComposition</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionComposition([NotNull] MppgParser.FunctionCompositionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMinimum</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMinimum([NotNull] MppgParser.FunctionMinimumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionRightExt</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionRightExt([NotNull] MppgParser.FunctionRightExtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMinPlusConvolution</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMinPlusConvolution([NotNull] MppgParser.FunctionMinPlusConvolutionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarMultiplicationLeft</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarMultiplicationLeft([NotNull] MppgParser.FunctionScalarMultiplicationLeftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSubtraction</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSubtraction([NotNull] MppgParser.FunctionSubtractionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionNonNegativeUpNonDecreasingClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionNonNegativeUpNonDecreasingClosure([NotNull] MppgParser.FunctionNonNegativeUpNonDecreasingClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionVariableExp</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVariableExp([NotNull] MppgParser.FunctionVariableExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarDivision</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarDivision([NotNull] MppgParser.FunctionScalarDivisionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionLeftExt</c>
	/// labeled alternative in <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionLeftExt([NotNull] MppgParser.FunctionLeftExtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionConstructor([NotNull] MppgParser.FunctionConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.rateLatency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateLatency([NotNull] MppgParser.RateLatencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.tokenBucket"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokenBucket([NotNull] MppgParser.TokenBucketContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.affineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAffineFunction([NotNull] MppgParser.AffineFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.stairFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStairFunction([NotNull] MppgParser.StairFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.delayFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelayFunction([NotNull] MppgParser.DelayFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.zeroFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZeroFunction([NotNull] MppgParser.ZeroFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberSub</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberSub([NotNull] MppgParser.NumberSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberReturningfunctionOperationExp</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberReturningfunctionOperationExp([NotNull] MppgParser.NumberReturningfunctionOperationExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberBrackets</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberBrackets([NotNull] MppgParser.NumberBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberVariableExp</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberVariableExp([NotNull] MppgParser.NumberVariableExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberSum</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberSum([NotNull] MppgParser.NumberSumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberMaximum</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberMaximum([NotNull] MppgParser.NumberMaximumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberMinimum</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberMinimum([NotNull] MppgParser.NumberMinimumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberMultiplication</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberMultiplication([NotNull] MppgParser.NumberMultiplicationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberLiteralExp</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteralExp([NotNull] MppgParser.NumberLiteralExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberDivision</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberDivision([NotNull] MppgParser.NumberDivisionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.numberReturningfunctionOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberReturningfunctionOperation([NotNull] MppgParser.NumberReturningfunctionOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionValueAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionValueAt([NotNull] MppgParser.FunctionValueAtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionHorizontalDeviation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionHorizontalDeviation([NotNull] MppgParser.FunctionHorizontalDeviationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionVerticalDeviation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVerticalDeviation([NotNull] MppgParser.FunctionVerticalDeviationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotCommand([NotNull] MppgParser.PlotCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionsToPlot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionsToPlot([NotNull] MppgParser.FunctionsToPlotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] MppgParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotArgs([NotNull] MppgParser.PlotArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotArg([NotNull] MppgParser.PlotArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] MppgParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterval([NotNull] MppgParser.IntervalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.printExpressionCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintExpressionCommand([NotNull] MppgParser.PrintExpressionCommandContext context);
}
} // namespace Unipi.MppgParser.Grammar
