//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Mppg.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Unipi.MppgParser.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class MppgParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, NEW_LINE=42, WHITE_SPACE=43, VARIABLE_NAME=44, 
		ASSIGN=45, STRING_LITERAL=46, COMMENT=47, NUMBER_LITERAL=48, RATIONAL_NUMBER_LITERAL=49, 
		DECIMAL_NUMBER_LITERAL=50, INFINITE_NUMBER_LITERAL=51;
	public const int
		RULE_program = 0, RULE_statement = 1, RULE_assignment = 2, RULE_expression = 3, 
		RULE_comment = 4, RULE_functionExpression = 5, RULE_functionConstructor = 6, 
		RULE_rateLatency = 7, RULE_tokenBucket = 8, RULE_affineFunction = 9, RULE_stairFunction = 10, 
		RULE_delayFunction = 11, RULE_zeroFunction = 12, RULE_pureConstantFunction = 13, 
		RULE_numberExpression = 14, RULE_numberReturningfunctionOperation = 15, 
		RULE_functionHorizontalDeviation = 16, RULE_functionVerticalDeviation = 17, 
		RULE_plotCommand = 18, RULE_functionsToPlot = 19, RULE_plotArgs = 20, 
		RULE_plotArg = 21, RULE_string = 22, RULE_interval = 23, RULE_printExpressionCommand = 24;
	public static readonly string[] ruleNames = {
		"program", "statement", "assignment", "expression", "comment", "functionExpression", 
		"functionConstructor", "rateLatency", "tokenBucket", "affineFunction", 
		"stairFunction", "delayFunction", "zeroFunction", "pureConstantFunction", 
		"numberExpression", "numberReturningfunctionOperation", "functionHorizontalDeviation", 
		"functionVerticalDeviation", "plotCommand", "functionsToPlot", "plotArgs", 
		"plotArg", "string", "interval", "printExpressionCommand"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'/\\'", "'\\/'", "'*'", "'*_'", "'*^'", "'/'", "'/_'", 
		"'/^'", "'comp'", "'+'", "'-'", "'star'", "'upclosure'", "'nnupclosure'", 
		"'left-ext'", "'right-ext'", "'ratency'", "','", "'bucket'", "'affine'", 
		"'stair'", "'delay'", "'zero'", "'hDev'", "'vDev'", "'plot'", "'main'", 
		"'='", "'xlim'", "'ylim'", "'xlab'", "'ylab'", "'out'", "'grid'", "'\"no\"'", 
		"'bg'", "'['", "']'", "'printExpression'", null, null, null, "':='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "NEW_LINE", "WHITE_SPACE", "VARIABLE_NAME", 
		"ASSIGN", "STRING_LITERAL", "COMMENT", "NUMBER_LITERAL", "RATIONAL_NUMBER_LITERAL", 
		"DECIMAL_NUMBER_LITERAL", "INFINITE_NUMBER_LITERAL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Mppg.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MppgParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MppgParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MppgParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MppgParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEW_LINE() { return GetTokens(MppgParser.NEW_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW_LINE(int i) {
			return GetToken(MppgParser.NEW_LINE, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			statement();
			State = 55;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 51;
					Match(NEW_LINE);
					State = 52;
					statement();
					}
					} 
				}
				State = 57;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NEW_LINE) {
				{
				State = 58;
				Match(NEW_LINE);
				}
			}

			State = 61;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotCommandContext plotCommand() {
			return GetRuleContext<PlotCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintExpressionCommandContext printExpressionCommand() {
			return GetRuleContext<PrintExpressionCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommentContext comment() {
			return GetRuleContext<CommentContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			State = 68;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 63;
				assignment();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64;
				expression();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 65;
				plotCommand();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 66;
				printExpressionCommand();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 67;
				comment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MppgParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 4, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(VARIABLE_NAME);
			State = 71;
			Match(ASSIGN);
			State = 72;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_expression);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 74;
				functionExpression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 75;
				numberExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(MppgParser.COMMENT, 0); }
		public CommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommentContext comment() {
		CommentContext _localctx = new CommentContext(Context, State);
		EnterRule(_localctx, 8, RULE_comment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionExpressionContext : ParserRuleContext {
		public FunctionExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionExpression; } }
	 
		public FunctionExpressionContext() { }
		public virtual void CopyFrom(FunctionExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FunctionMaximumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaximumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaximum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMaxPlusDeconvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaxPlusDeconvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaxPlusDeconvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMaxPlusConvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaxPlusConvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaxPlusConvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionSumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionBracketsContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionBracketsContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionBrackets(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarMultiplicationRightContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionScalarMultiplicationRightContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarMultiplicationRight(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinPlusDeconvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinPlusDeconvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinPlusDeconvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionUpNonDecreasingClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionUpNonDecreasingClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionUpNonDecreasingClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionConstructorExpContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionConstructorContext functionConstructor() {
			return GetRuleContext<FunctionConstructorContext>(0);
		}
		public FunctionConstructorExpContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionConstructorExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSubadditiveClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionSubadditiveClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSubadditiveClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionCompositionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionCompositionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionComposition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinimumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinimumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinimum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionRightExtContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionRightExtContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionRightExt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinPlusConvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinPlusConvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinPlusConvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarMultiplicationLeftContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionScalarMultiplicationLeftContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarMultiplicationLeft(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSubtractionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionSubtractionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSubtraction(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionNonNegativeUpNonDecreasingClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionNonNegativeUpNonDecreasingClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionNonNegativeUpNonDecreasingClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionVariableExpContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public FunctionVariableExpContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarDivisionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionScalarDivisionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarDivision(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionLeftExtContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionLeftExtContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionLeftExt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionExpressionContext functionExpression() {
		return functionExpression(0);
	}

	private FunctionExpressionContext functionExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		FunctionExpressionContext _localctx = new FunctionExpressionContext(Context, _parentState);
		FunctionExpressionContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_functionExpression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				_localctx = new FunctionBracketsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 81;
				Match(T__0);
				State = 82;
				functionExpression(0);
				State = 83;
				Match(T__1);
				}
				break;
			case 2:
				{
				_localctx = new FunctionScalarMultiplicationRightContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 85;
				numberExpression(0);
				State = 86;
				Match(T__4);
				State = 87;
				functionExpression(11);
				}
				break;
			case 3:
				{
				_localctx = new FunctionConstructorExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 89;
				functionConstructor();
				}
				break;
			case 4:
				{
				_localctx = new FunctionSubadditiveClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 90;
				Match(T__13);
				State = 91;
				Match(T__0);
				State = 92;
				functionExpression(0);
				State = 93;
				Match(T__1);
				}
				break;
			case 5:
				{
				_localctx = new FunctionUpNonDecreasingClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 95;
				Match(T__14);
				State = 96;
				Match(T__0);
				State = 97;
				functionExpression(0);
				State = 98;
				Match(T__1);
				}
				break;
			case 6:
				{
				_localctx = new FunctionNonNegativeUpNonDecreasingClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 100;
				Match(T__15);
				State = 101;
				Match(T__0);
				State = 102;
				functionExpression(0);
				State = 103;
				Match(T__1);
				}
				break;
			case 7:
				{
				_localctx = new FunctionLeftExtContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 105;
				Match(T__16);
				State = 106;
				Match(T__0);
				State = 107;
				functionExpression(0);
				State = 108;
				Match(T__1);
				}
				break;
			case 8:
				{
				_localctx = new FunctionRightExtContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 110;
				Match(T__17);
				State = 111;
				Match(T__0);
				State = 112;
				functionExpression(0);
				State = 113;
				Match(T__1);
				}
				break;
			case 9:
				{
				_localctx = new FunctionVariableExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 115;
				Match(VARIABLE_NAME);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 153;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 151;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
					case 1:
						{
						_localctx = new FunctionMinimumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 118;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 119;
						Match(T__2);
						State = 120;
						functionExpression(20);
						}
						break;
					case 2:
						{
						_localctx = new FunctionMaximumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 121;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 122;
						Match(T__3);
						State = 123;
						functionExpression(19);
						}
						break;
					case 3:
						{
						_localctx = new FunctionMinPlusConvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 124;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 125;
						_la = TokenStream.LA(1);
						if ( !(_la==T__4 || _la==T__5) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 126;
						functionExpression(18);
						}
						break;
					case 4:
						{
						_localctx = new FunctionMaxPlusConvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 127;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 128;
						Match(T__6);
						State = 129;
						functionExpression(17);
						}
						break;
					case 5:
						{
						_localctx = new FunctionMinPlusDeconvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 130;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 131;
						_la = TokenStream.LA(1);
						if ( !(_la==T__7 || _la==T__8) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 132;
						functionExpression(16);
						}
						break;
					case 6:
						{
						_localctx = new FunctionMaxPlusDeconvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 133;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 134;
						Match(T__9);
						State = 135;
						functionExpression(15);
						}
						break;
					case 7:
						{
						_localctx = new FunctionCompositionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 136;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 137;
						Match(T__10);
						State = 138;
						functionExpression(14);
						}
						break;
					case 8:
						{
						_localctx = new FunctionSumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 139;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 140;
						Match(T__11);
						State = 141;
						functionExpression(10);
						}
						break;
					case 9:
						{
						_localctx = new FunctionSubtractionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 142;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 143;
						Match(T__12);
						State = 144;
						functionExpression(9);
						}
						break;
					case 10:
						{
						_localctx = new FunctionScalarMultiplicationLeftContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 145;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 146;
						Match(T__4);
						State = 147;
						numberExpression(0);
						}
						break;
					case 11:
						{
						_localctx = new FunctionScalarDivisionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 148;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 149;
						Match(T__7);
						State = 150;
						numberExpression(0);
						}
						break;
					}
					} 
				}
				State = 155;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FunctionConstructorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RateLatencyContext rateLatency() {
			return GetRuleContext<RateLatencyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TokenBucketContext tokenBucket() {
			return GetRuleContext<TokenBucketContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AffineFunctionContext affineFunction() {
			return GetRuleContext<AffineFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StairFunctionContext stairFunction() {
			return GetRuleContext<StairFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DelayFunctionContext delayFunction() {
			return GetRuleContext<DelayFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ZeroFunctionContext zeroFunction() {
			return GetRuleContext<ZeroFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PureConstantFunctionContext pureConstantFunction() {
			return GetRuleContext<PureConstantFunctionContext>(0);
		}
		public FunctionConstructorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionConstructor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionConstructor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionConstructorContext functionConstructor() {
		FunctionConstructorContext _localctx = new FunctionConstructorContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionConstructor);
		try {
			State = 163;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
				EnterOuterAlt(_localctx, 1);
				{
				State = 156;
				rateLatency();
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 2);
				{
				State = 157;
				tokenBucket();
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 3);
				{
				State = 158;
				affineFunction();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 4);
				{
				State = 159;
				stairFunction();
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 5);
				{
				State = 160;
				delayFunction();
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 6);
				{
				State = 161;
				zeroFunction();
				}
				break;
			case T__0:
			case T__25:
			case T__26:
			case VARIABLE_NAME:
			case NUMBER_LITERAL:
				EnterOuterAlt(_localctx, 7);
				{
				State = 162;
				pureConstantFunction();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RateLatencyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public RateLatencyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rateLatency; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRateLatency(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RateLatencyContext rateLatency() {
		RateLatencyContext _localctx = new RateLatencyContext(Context, State);
		EnterRule(_localctx, 14, RULE_rateLatency);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 165;
			Match(T__18);
			State = 166;
			Match(T__0);
			State = 167;
			numberExpression(0);
			State = 168;
			Match(T__19);
			State = 169;
			numberExpression(0);
			State = 170;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TokenBucketContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public TokenBucketContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tokenBucket; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTokenBucket(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TokenBucketContext tokenBucket() {
		TokenBucketContext _localctx = new TokenBucketContext(Context, State);
		EnterRule(_localctx, 16, RULE_tokenBucket);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172;
			Match(T__20);
			State = 173;
			Match(T__0);
			State = 174;
			numberExpression(0);
			State = 175;
			Match(T__19);
			State = 176;
			numberExpression(0);
			State = 177;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AffineFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public AffineFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_affineFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAffineFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AffineFunctionContext affineFunction() {
		AffineFunctionContext _localctx = new AffineFunctionContext(Context, State);
		EnterRule(_localctx, 18, RULE_affineFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			Match(T__21);
			State = 180;
			Match(T__0);
			State = 181;
			numberExpression(0);
			State = 182;
			Match(T__19);
			State = 183;
			numberExpression(0);
			State = 184;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StairFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public StairFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stairFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStairFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StairFunctionContext stairFunction() {
		StairFunctionContext _localctx = new StairFunctionContext(Context, State);
		EnterRule(_localctx, 20, RULE_stairFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			Match(T__22);
			State = 187;
			Match(T__0);
			State = 188;
			numberExpression(0);
			State = 189;
			Match(T__19);
			State = 190;
			numberExpression(0);
			State = 191;
			Match(T__19);
			State = 192;
			numberExpression(0);
			State = 193;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DelayFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public DelayFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_delayFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDelayFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DelayFunctionContext delayFunction() {
		DelayFunctionContext _localctx = new DelayFunctionContext(Context, State);
		EnterRule(_localctx, 22, RULE_delayFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195;
			Match(T__23);
			State = 196;
			Match(T__0);
			State = 197;
			numberExpression(0);
			State = 198;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ZeroFunctionContext : ParserRuleContext {
		public ZeroFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_zeroFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitZeroFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ZeroFunctionContext zeroFunction() {
		ZeroFunctionContext _localctx = new ZeroFunctionContext(Context, State);
		EnterRule(_localctx, 24, RULE_zeroFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			Match(T__24);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PureConstantFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public PureConstantFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pureConstantFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPureConstantFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PureConstantFunctionContext pureConstantFunction() {
		PureConstantFunctionContext _localctx = new PureConstantFunctionContext(Context, State);
		EnterRule(_localctx, 26, RULE_pureConstantFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 202;
			numberExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberExpressionContext : ParserRuleContext {
		public NumberExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberExpression; } }
	 
		public NumberExpressionContext() { }
		public virtual void CopyFrom(NumberExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberReturningfunctionOperationExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberReturningfunctionOperationContext numberReturningfunctionOperation() {
			return GetRuleContext<NumberReturningfunctionOperationContext>(0);
		}
		public NumberReturningfunctionOperationExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberReturningfunctionOperationExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberBracketsContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public NumberBracketsContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberBrackets(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberVariableExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public NumberVariableExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberSumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberSumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberSum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMaximumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMaximumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMaximum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMinimumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMinimumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMinimum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMultiplicationContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMultiplicationContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMultiplication(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberLiteralExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(MppgParser.NUMBER_LITERAL, 0); }
		public NumberLiteralExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberLiteralExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberDivisionContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberDivisionContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberDivision(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberExpressionContext numberExpression() {
		return numberExpression(0);
	}

	private NumberExpressionContext numberExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		NumberExpressionContext _localctx = new NumberExpressionContext(Context, _parentState);
		NumberExpressionContext _prevctx = _localctx;
		int _startState = 28;
		EnterRecursionRule(_localctx, 28, RULE_numberExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 212;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
			case T__26:
				{
				_localctx = new NumberReturningfunctionOperationExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 205;
				numberReturningfunctionOperation();
				}
				break;
			case T__0:
				{
				_localctx = new NumberBracketsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 206;
				Match(T__0);
				State = 207;
				numberExpression(0);
				State = 208;
				Match(T__1);
				}
				break;
			case VARIABLE_NAME:
				{
				_localctx = new NumberVariableExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 210;
				Match(VARIABLE_NAME);
				}
				break;
			case NUMBER_LITERAL:
				{
				_localctx = new NumberLiteralExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 211;
				Match(NUMBER_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 231;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 229;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
					case 1:
						{
						_localctx = new NumberMultiplicationContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 214;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 215;
						Match(T__4);
						State = 216;
						numberExpression(8);
						}
						break;
					case 2:
						{
						_localctx = new NumberDivisionContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 217;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 218;
						Match(T__7);
						State = 219;
						numberExpression(7);
						}
						break;
					case 3:
						{
						_localctx = new NumberSumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 220;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 221;
						Match(T__11);
						State = 222;
						numberExpression(6);
						}
						break;
					case 4:
						{
						_localctx = new NumberMinimumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 223;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 224;
						Match(T__2);
						State = 225;
						numberExpression(5);
						}
						break;
					case 5:
						{
						_localctx = new NumberMaximumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 226;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 227;
						Match(T__3);
						State = 228;
						numberExpression(4);
						}
						break;
					}
					} 
				}
				State = 233;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumberReturningfunctionOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionHorizontalDeviationContext functionHorizontalDeviation() {
			return GetRuleContext<FunctionHorizontalDeviationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionVerticalDeviationContext functionVerticalDeviation() {
			return GetRuleContext<FunctionVerticalDeviationContext>(0);
		}
		public NumberReturningfunctionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberReturningfunctionOperation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberReturningfunctionOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberReturningfunctionOperationContext numberReturningfunctionOperation() {
		NumberReturningfunctionOperationContext _localctx = new NumberReturningfunctionOperationContext(Context, State);
		EnterRule(_localctx, 30, RULE_numberReturningfunctionOperation);
		try {
			State = 236;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
				EnterOuterAlt(_localctx, 1);
				{
				State = 234;
				functionHorizontalDeviation();
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 2);
				{
				State = 235;
				functionVerticalDeviation();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionHorizontalDeviationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionHorizontalDeviationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionHorizontalDeviation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionHorizontalDeviation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionHorizontalDeviationContext functionHorizontalDeviation() {
		FunctionHorizontalDeviationContext _localctx = new FunctionHorizontalDeviationContext(Context, State);
		EnterRule(_localctx, 32, RULE_functionHorizontalDeviation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238;
			Match(T__25);
			State = 239;
			Match(T__0);
			State = 240;
			functionExpression(0);
			State = 241;
			Match(T__19);
			State = 242;
			functionExpression(0);
			State = 243;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionVerticalDeviationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionVerticalDeviationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionVerticalDeviation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionVerticalDeviation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionVerticalDeviationContext functionVerticalDeviation() {
		FunctionVerticalDeviationContext _localctx = new FunctionVerticalDeviationContext(Context, State);
		EnterRule(_localctx, 34, RULE_functionVerticalDeviation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 245;
			Match(T__26);
			State = 246;
			Match(T__0);
			State = 247;
			functionExpression(0);
			State = 248;
			Match(T__19);
			State = 249;
			functionExpression(0);
			State = 250;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionsToPlotContext functionsToPlot() {
			return GetRuleContext<FunctionsToPlotContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgsContext plotArgs() {
			return GetRuleContext<PlotArgsContext>(0);
		}
		public PlotCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotCommandContext plotCommand() {
		PlotCommandContext _localctx = new PlotCommandContext(Context, State);
		EnterRule(_localctx, 36, RULE_plotCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 252;
			Match(T__27);
			State = 253;
			Match(T__0);
			State = 254;
			functionsToPlot();
			State = 257;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__19) {
				{
				State = 255;
				Match(T__19);
				State = 256;
				plotArgs();
				}
			}

			State = 259;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionsToPlotContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(MppgParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(MppgParser.VARIABLE_NAME, i);
		}
		public FunctionsToPlotContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionsToPlot; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionsToPlot(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionsToPlotContext functionsToPlot() {
		FunctionsToPlotContext _localctx = new FunctionsToPlotContext(Context, State);
		EnterRule(_localctx, 38, RULE_functionsToPlot);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 261;
			Match(VARIABLE_NAME);
			State = 266;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 262;
					Match(T__19);
					State = 263;
					Match(VARIABLE_NAME);
					}
					} 
				}
				State = 268;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgContext[] plotArg() {
			return GetRuleContexts<PlotArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgContext plotArg(int i) {
			return GetRuleContext<PlotArgContext>(i);
		}
		public PlotArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotArgsContext plotArgs() {
		PlotArgsContext _localctx = new PlotArgsContext(Context, State);
		EnterRule(_localctx, 40, RULE_plotArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 269;
			plotArg();
			State = 274;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__19) {
				{
				{
				State = 270;
				Match(T__19);
				State = 271;
				plotArg();
				}
				}
				State = 276;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IntervalContext interval() {
			return GetRuleContext<IntervalContext>(0);
		}
		public PlotArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotArgContext plotArg() {
		PlotArgContext _localctx = new PlotArgContext(Context, State);
		EnterRule(_localctx, 42, RULE_plotArg);
		try {
			State = 301;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__28:
				EnterOuterAlt(_localctx, 1);
				{
				State = 277;
				Match(T__28);
				State = 278;
				Match(T__29);
				State = 279;
				@string(0);
				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 2);
				{
				State = 280;
				Match(T__30);
				State = 281;
				Match(T__29);
				State = 282;
				interval();
				}
				break;
			case T__31:
				EnterOuterAlt(_localctx, 3);
				{
				State = 283;
				Match(T__31);
				State = 284;
				Match(T__29);
				State = 285;
				interval();
				}
				break;
			case T__32:
				EnterOuterAlt(_localctx, 4);
				{
				State = 286;
				Match(T__32);
				State = 287;
				Match(T__29);
				State = 288;
				@string(0);
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 5);
				{
				State = 289;
				Match(T__33);
				State = 290;
				Match(T__29);
				State = 291;
				@string(0);
				}
				break;
			case T__34:
				EnterOuterAlt(_localctx, 6);
				{
				State = 292;
				Match(T__34);
				State = 293;
				Match(T__29);
				State = 294;
				@string(0);
				}
				break;
			case T__35:
				EnterOuterAlt(_localctx, 7);
				{
				State = 295;
				Match(T__35);
				State = 296;
				Match(T__29);
				State = 297;
				Match(T__36);
				}
				break;
			case T__37:
				EnterOuterAlt(_localctx, 8);
				{
				State = 298;
				Match(T__37);
				State = 299;
				Match(T__29);
				State = 300;
				Match(T__36);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(MppgParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(MppgParser.NUMBER_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		return @string(0);
	}

	private StringContext @string(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		StringContext _localctx = new StringContext(Context, _parentState);
		StringContext _prevctx = _localctx;
		int _startState = 44;
		EnterRecursionRule(_localctx, 44, RULE_string, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 307;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING_LITERAL:
				{
				State = 304;
				Match(STRING_LITERAL);
				}
				break;
			case VARIABLE_NAME:
				{
				State = 305;
				Match(VARIABLE_NAME);
				}
				break;
			case NUMBER_LITERAL:
				{
				State = 306;
				Match(NUMBER_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 314;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new StringContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_string);
					State = 309;
					if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
					State = 310;
					Match(T__11);
					State = 311;
					@string(5);
					}
					} 
				}
				State = 316;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class IntervalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER_LITERAL() { return GetTokens(MppgParser.NUMBER_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL(int i) {
			return GetToken(MppgParser.NUMBER_LITERAL, i);
		}
		public IntervalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interval; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterval(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntervalContext interval() {
		IntervalContext _localctx = new IntervalContext(Context, State);
		EnterRule(_localctx, 46, RULE_interval);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 317;
			Match(T__38);
			State = 318;
			Match(NUMBER_LITERAL);
			State = 319;
			Match(T__19);
			State = 320;
			Match(NUMBER_LITERAL);
			State = 321;
			Match(T__39);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintExpressionCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public PrintExpressionCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_printExpressionCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrintExpressionCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintExpressionCommandContext printExpressionCommand() {
		PrintExpressionCommandContext _localctx = new PrintExpressionCommandContext(Context, State);
		EnterRule(_localctx, 48, RULE_printExpressionCommand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 323;
			Match(T__40);
			State = 324;
			Match(T__0);
			State = 325;
			Match(VARIABLE_NAME);
			State = 326;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return functionExpression_sempred((FunctionExpressionContext)_localctx, predIndex);
		case 14: return numberExpression_sempred((NumberExpressionContext)_localctx, predIndex);
		case 22: return string_sempred((StringContext)_localctx, predIndex);
		}
		return true;
	}
	private bool functionExpression_sempred(FunctionExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 19);
		case 1: return Precpred(Context, 18);
		case 2: return Precpred(Context, 17);
		case 3: return Precpred(Context, 16);
		case 4: return Precpred(Context, 15);
		case 5: return Precpred(Context, 14);
		case 6: return Precpred(Context, 13);
		case 7: return Precpred(Context, 9);
		case 8: return Precpred(Context, 8);
		case 9: return Precpred(Context, 12);
		case 10: return Precpred(Context, 10);
		}
		return true;
	}
	private bool numberExpression_sempred(NumberExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 11: return Precpred(Context, 7);
		case 12: return Precpred(Context, 6);
		case 13: return Precpred(Context, 5);
		case 14: return Precpred(Context, 4);
		case 15: return Precpred(Context, 3);
		}
		return true;
	}
	private bool string_sempred(StringContext _localctx, int predIndex) {
		switch (predIndex) {
		case 16: return Precpred(Context, 4);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,51,329,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,1,0,1,0,1,0,5,0,54,8,0,10,0,12,0,57,9,0,
		1,0,3,0,60,8,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,3,1,69,8,1,1,2,1,2,1,2,1,2,
		1,3,1,3,3,3,77,8,3,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,117,8,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,5,5,152,8,5,10,5,12,5,155,9,5,1,6,1,
		6,1,6,1,6,1,6,1,6,1,6,3,6,164,8,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,8,1,8,
		1,8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,1,11,1,12,1,12,1,13,1,13,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,213,8,14,1,14,1,14,1,14,1,14,
		1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,5,14,230,8,14,10,
		14,12,14,233,9,14,1,15,1,15,3,15,237,8,15,1,16,1,16,1,16,1,16,1,16,1,16,
		1,16,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,18,1,18,1,18,1,18,1,18,3,18,
		258,8,18,1,18,1,18,1,19,1,19,1,19,5,19,265,8,19,10,19,12,19,268,9,19,1,
		20,1,20,1,20,5,20,273,8,20,10,20,12,20,276,9,20,1,21,1,21,1,21,1,21,1,
		21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,
		21,1,21,1,21,1,21,1,21,1,21,3,21,302,8,21,1,22,1,22,1,22,1,22,3,22,308,
		8,22,1,22,1,22,1,22,5,22,313,8,22,10,22,12,22,316,9,22,1,23,1,23,1,23,
		1,23,1,23,1,23,1,24,1,24,1,24,1,24,1,24,1,24,0,3,10,28,44,25,0,2,4,6,8,
		10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,0,2,1,0,5,
		6,1,0,8,9,357,0,50,1,0,0,0,2,68,1,0,0,0,4,70,1,0,0,0,6,76,1,0,0,0,8,78,
		1,0,0,0,10,116,1,0,0,0,12,163,1,0,0,0,14,165,1,0,0,0,16,172,1,0,0,0,18,
		179,1,0,0,0,20,186,1,0,0,0,22,195,1,0,0,0,24,200,1,0,0,0,26,202,1,0,0,
		0,28,212,1,0,0,0,30,236,1,0,0,0,32,238,1,0,0,0,34,245,1,0,0,0,36,252,1,
		0,0,0,38,261,1,0,0,0,40,269,1,0,0,0,42,301,1,0,0,0,44,307,1,0,0,0,46,317,
		1,0,0,0,48,323,1,0,0,0,50,55,3,2,1,0,51,52,5,42,0,0,52,54,3,2,1,0,53,51,
		1,0,0,0,54,57,1,0,0,0,55,53,1,0,0,0,55,56,1,0,0,0,56,59,1,0,0,0,57,55,
		1,0,0,0,58,60,5,42,0,0,59,58,1,0,0,0,59,60,1,0,0,0,60,61,1,0,0,0,61,62,
		5,0,0,1,62,1,1,0,0,0,63,69,3,4,2,0,64,69,3,6,3,0,65,69,3,36,18,0,66,69,
		3,48,24,0,67,69,3,8,4,0,68,63,1,0,0,0,68,64,1,0,0,0,68,65,1,0,0,0,68,66,
		1,0,0,0,68,67,1,0,0,0,69,3,1,0,0,0,70,71,5,44,0,0,71,72,5,45,0,0,72,73,
		3,6,3,0,73,5,1,0,0,0,74,77,3,10,5,0,75,77,3,28,14,0,76,74,1,0,0,0,76,75,
		1,0,0,0,77,7,1,0,0,0,78,79,5,47,0,0,79,9,1,0,0,0,80,81,6,5,-1,0,81,82,
		5,1,0,0,82,83,3,10,5,0,83,84,5,2,0,0,84,117,1,0,0,0,85,86,3,28,14,0,86,
		87,5,5,0,0,87,88,3,10,5,11,88,117,1,0,0,0,89,117,3,12,6,0,90,91,5,14,0,
		0,91,92,5,1,0,0,92,93,3,10,5,0,93,94,5,2,0,0,94,117,1,0,0,0,95,96,5,15,
		0,0,96,97,5,1,0,0,97,98,3,10,5,0,98,99,5,2,0,0,99,117,1,0,0,0,100,101,
		5,16,0,0,101,102,5,1,0,0,102,103,3,10,5,0,103,104,5,2,0,0,104,117,1,0,
		0,0,105,106,5,17,0,0,106,107,5,1,0,0,107,108,3,10,5,0,108,109,5,2,0,0,
		109,117,1,0,0,0,110,111,5,18,0,0,111,112,5,1,0,0,112,113,3,10,5,0,113,
		114,5,2,0,0,114,117,1,0,0,0,115,117,5,44,0,0,116,80,1,0,0,0,116,85,1,0,
		0,0,116,89,1,0,0,0,116,90,1,0,0,0,116,95,1,0,0,0,116,100,1,0,0,0,116,105,
		1,0,0,0,116,110,1,0,0,0,116,115,1,0,0,0,117,153,1,0,0,0,118,119,10,19,
		0,0,119,120,5,3,0,0,120,152,3,10,5,20,121,122,10,18,0,0,122,123,5,4,0,
		0,123,152,3,10,5,19,124,125,10,17,0,0,125,126,7,0,0,0,126,152,3,10,5,18,
		127,128,10,16,0,0,128,129,5,7,0,0,129,152,3,10,5,17,130,131,10,15,0,0,
		131,132,7,1,0,0,132,152,3,10,5,16,133,134,10,14,0,0,134,135,5,10,0,0,135,
		152,3,10,5,15,136,137,10,13,0,0,137,138,5,11,0,0,138,152,3,10,5,14,139,
		140,10,9,0,0,140,141,5,12,0,0,141,152,3,10,5,10,142,143,10,8,0,0,143,144,
		5,13,0,0,144,152,3,10,5,9,145,146,10,12,0,0,146,147,5,5,0,0,147,152,3,
		28,14,0,148,149,10,10,0,0,149,150,5,8,0,0,150,152,3,28,14,0,151,118,1,
		0,0,0,151,121,1,0,0,0,151,124,1,0,0,0,151,127,1,0,0,0,151,130,1,0,0,0,
		151,133,1,0,0,0,151,136,1,0,0,0,151,139,1,0,0,0,151,142,1,0,0,0,151,145,
		1,0,0,0,151,148,1,0,0,0,152,155,1,0,0,0,153,151,1,0,0,0,153,154,1,0,0,
		0,154,11,1,0,0,0,155,153,1,0,0,0,156,164,3,14,7,0,157,164,3,16,8,0,158,
		164,3,18,9,0,159,164,3,20,10,0,160,164,3,22,11,0,161,164,3,24,12,0,162,
		164,3,26,13,0,163,156,1,0,0,0,163,157,1,0,0,0,163,158,1,0,0,0,163,159,
		1,0,0,0,163,160,1,0,0,0,163,161,1,0,0,0,163,162,1,0,0,0,164,13,1,0,0,0,
		165,166,5,19,0,0,166,167,5,1,0,0,167,168,3,28,14,0,168,169,5,20,0,0,169,
		170,3,28,14,0,170,171,5,2,0,0,171,15,1,0,0,0,172,173,5,21,0,0,173,174,
		5,1,0,0,174,175,3,28,14,0,175,176,5,20,0,0,176,177,3,28,14,0,177,178,5,
		2,0,0,178,17,1,0,0,0,179,180,5,22,0,0,180,181,5,1,0,0,181,182,3,28,14,
		0,182,183,5,20,0,0,183,184,3,28,14,0,184,185,5,2,0,0,185,19,1,0,0,0,186,
		187,5,23,0,0,187,188,5,1,0,0,188,189,3,28,14,0,189,190,5,20,0,0,190,191,
		3,28,14,0,191,192,5,20,0,0,192,193,3,28,14,0,193,194,5,2,0,0,194,21,1,
		0,0,0,195,196,5,24,0,0,196,197,5,1,0,0,197,198,3,28,14,0,198,199,5,2,0,
		0,199,23,1,0,0,0,200,201,5,25,0,0,201,25,1,0,0,0,202,203,3,28,14,0,203,
		27,1,0,0,0,204,205,6,14,-1,0,205,213,3,30,15,0,206,207,5,1,0,0,207,208,
		3,28,14,0,208,209,5,2,0,0,209,213,1,0,0,0,210,213,5,44,0,0,211,213,5,48,
		0,0,212,204,1,0,0,0,212,206,1,0,0,0,212,210,1,0,0,0,212,211,1,0,0,0,213,
		231,1,0,0,0,214,215,10,7,0,0,215,216,5,5,0,0,216,230,3,28,14,8,217,218,
		10,6,0,0,218,219,5,8,0,0,219,230,3,28,14,7,220,221,10,5,0,0,221,222,5,
		12,0,0,222,230,3,28,14,6,223,224,10,4,0,0,224,225,5,3,0,0,225,230,3,28,
		14,5,226,227,10,3,0,0,227,228,5,4,0,0,228,230,3,28,14,4,229,214,1,0,0,
		0,229,217,1,0,0,0,229,220,1,0,0,0,229,223,1,0,0,0,229,226,1,0,0,0,230,
		233,1,0,0,0,231,229,1,0,0,0,231,232,1,0,0,0,232,29,1,0,0,0,233,231,1,0,
		0,0,234,237,3,32,16,0,235,237,3,34,17,0,236,234,1,0,0,0,236,235,1,0,0,
		0,237,31,1,0,0,0,238,239,5,26,0,0,239,240,5,1,0,0,240,241,3,10,5,0,241,
		242,5,20,0,0,242,243,3,10,5,0,243,244,5,2,0,0,244,33,1,0,0,0,245,246,5,
		27,0,0,246,247,5,1,0,0,247,248,3,10,5,0,248,249,5,20,0,0,249,250,3,10,
		5,0,250,251,5,2,0,0,251,35,1,0,0,0,252,253,5,28,0,0,253,254,5,1,0,0,254,
		257,3,38,19,0,255,256,5,20,0,0,256,258,3,40,20,0,257,255,1,0,0,0,257,258,
		1,0,0,0,258,259,1,0,0,0,259,260,5,2,0,0,260,37,1,0,0,0,261,266,5,44,0,
		0,262,263,5,20,0,0,263,265,5,44,0,0,264,262,1,0,0,0,265,268,1,0,0,0,266,
		264,1,0,0,0,266,267,1,0,0,0,267,39,1,0,0,0,268,266,1,0,0,0,269,274,3,42,
		21,0,270,271,5,20,0,0,271,273,3,42,21,0,272,270,1,0,0,0,273,276,1,0,0,
		0,274,272,1,0,0,0,274,275,1,0,0,0,275,41,1,0,0,0,276,274,1,0,0,0,277,278,
		5,29,0,0,278,279,5,30,0,0,279,302,3,44,22,0,280,281,5,31,0,0,281,282,5,
		30,0,0,282,302,3,46,23,0,283,284,5,32,0,0,284,285,5,30,0,0,285,302,3,46,
		23,0,286,287,5,33,0,0,287,288,5,30,0,0,288,302,3,44,22,0,289,290,5,34,
		0,0,290,291,5,30,0,0,291,302,3,44,22,0,292,293,5,35,0,0,293,294,5,30,0,
		0,294,302,3,44,22,0,295,296,5,36,0,0,296,297,5,30,0,0,297,302,5,37,0,0,
		298,299,5,38,0,0,299,300,5,30,0,0,300,302,5,37,0,0,301,277,1,0,0,0,301,
		280,1,0,0,0,301,283,1,0,0,0,301,286,1,0,0,0,301,289,1,0,0,0,301,292,1,
		0,0,0,301,295,1,0,0,0,301,298,1,0,0,0,302,43,1,0,0,0,303,304,6,22,-1,0,
		304,308,5,46,0,0,305,308,5,44,0,0,306,308,5,48,0,0,307,303,1,0,0,0,307,
		305,1,0,0,0,307,306,1,0,0,0,308,314,1,0,0,0,309,310,10,4,0,0,310,311,5,
		12,0,0,311,313,3,44,22,5,312,309,1,0,0,0,313,316,1,0,0,0,314,312,1,0,0,
		0,314,315,1,0,0,0,315,45,1,0,0,0,316,314,1,0,0,0,317,318,5,39,0,0,318,
		319,5,48,0,0,319,320,5,20,0,0,320,321,5,48,0,0,321,322,5,40,0,0,322,47,
		1,0,0,0,323,324,5,41,0,0,324,325,5,1,0,0,325,326,5,44,0,0,326,327,5,2,
		0,0,327,49,1,0,0,0,18,55,59,68,76,116,151,153,163,212,229,231,236,257,
		266,274,301,307,314
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Unipi.MppgParser.Grammar
