//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Mppg.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Unipi.MppgParser.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class MppgParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, NEW_LINE=38, 
		WHITE_SPACE=39, VARIABLE_NAME=40, ASSIGN=41, STRING_LITERAL=42, NUMBER_LITERAL=43, 
		RATIONAL_NUMBER_LITERAL=44, DECIMAL_NUMBER_LITERAL=45, INFINITE_NUMBER_LITERAL=46;
	public const int
		RULE_program = 0, RULE_statement = 1, RULE_assignment = 2, RULE_expression = 3, 
		RULE_comment = 4, RULE_functionExpression = 5, RULE_functionConstructor = 6, 
		RULE_rateLatency = 7, RULE_tokenBucket = 8, RULE_affineFunction = 9, RULE_stairFunction = 10, 
		RULE_zeroFunction = 11, RULE_numberExpression = 12, RULE_numberReturningfunctionOperation = 13, 
		RULE_functionHorizontalDeviation = 14, RULE_functionVerticalDeviation = 15, 
		RULE_plotCommand = 16, RULE_functionsToPlot = 17, RULE_plotArgs = 18, 
		RULE_plotArg = 19, RULE_string = 20, RULE_interval = 21, RULE_printExpressionCommand = 22;
	public static readonly string[] ruleNames = {
		"program", "statement", "assignment", "expression", "comment", "functionExpression", 
		"functionConstructor", "rateLatency", "tokenBucket", "affineFunction", 
		"stairFunction", "zeroFunction", "numberExpression", "numberReturningfunctionOperation", 
		"functionHorizontalDeviation", "functionVerticalDeviation", "plotCommand", 
		"functionsToPlot", "plotArgs", "plotArg", "string", "interval", "printExpressionCommand"
	};

	private static readonly string[] _LiteralNames = {
		null, "'// '", "'('", "')'", "'*'", "'*_'", "'*^'", "'/'", "'/_'", "'/^'", 
		"'comp'", "'+'", "'-'", "'star'", "'left-ext'", "'right-ext'", "'ratency'", 
		"','", "'bucket'", "'affine'", "'stair'", "'zero'", "'hDev'", "'vDev'", 
		"'plot'", "'main'", "'='", "'xlim'", "'ylim'", "'xlab'", "'ylab'", "'out'", 
		"'grid'", "'\"no\"'", "'bg'", "'['", "']'", "'printExpression'", null, 
		null, null, "':='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "NEW_LINE", "WHITE_SPACE", "VARIABLE_NAME", "ASSIGN", "STRING_LITERAL", 
		"NUMBER_LITERAL", "RATIONAL_NUMBER_LITERAL", "DECIMAL_NUMBER_LITERAL", 
		"INFINITE_NUMBER_LITERAL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Mppg.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MppgParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MppgParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MppgParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MppgParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEW_LINE() { return GetTokens(MppgParser.NEW_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW_LINE(int i) {
			return GetToken(MppgParser.NEW_LINE, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 46;
			statement();
			State = 51;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 47;
					Match(NEW_LINE);
					State = 48;
					statement();
					}
					} 
				}
				State = 53;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 55;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NEW_LINE) {
				{
				State = 54;
				Match(NEW_LINE);
				}
			}

			State = 57;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotCommandContext plotCommand() {
			return GetRuleContext<PlotCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintExpressionCommandContext printExpressionCommand() {
			return GetRuleContext<PrintExpressionCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommentContext comment() {
			return GetRuleContext<CommentContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			State = 64;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 59;
				assignment();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 60;
				expression();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 61;
				plotCommand();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 62;
				printExpressionCommand();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 63;
				comment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MppgParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 4, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66;
			Match(VARIABLE_NAME);
			State = 67;
			Match(ASSIGN);
			State = 68;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_expression);
		try {
			State = 72;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 70;
				functionExpression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 71;
				numberExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEW_LINE() { return GetTokens(MppgParser.NEW_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW_LINE(int i) {
			return GetToken(MppgParser.NEW_LINE, i);
		}
		public CommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommentContext comment() {
		CommentContext _localctx = new CommentContext(Context, State);
		EnterRule(_localctx, 8, RULE_comment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			Match(T__0);
			State = 76;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 75;
				_la = TokenStream.LA(1);
				if ( _la <= 0 || (_la==NEW_LINE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 140462610448382L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionExpressionContext : ParserRuleContext {
		public FunctionExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionExpression; } }
	 
		public FunctionExpressionContext() { }
		public virtual void CopyFrom(FunctionExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FunctionMaxPlusDeconvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaxPlusDeconvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaxPlusDeconvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMaxPlusConvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaxPlusConvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaxPlusConvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionSumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionBracketsContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionBracketsContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionBrackets(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarMultiplicationRightContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionScalarMultiplicationRightContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarMultiplicationRight(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinPlusDeconvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinPlusDeconvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinPlusDeconvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionConstructorExpContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionConstructorContext functionConstructor() {
			return GetRuleContext<FunctionConstructorContext>(0);
		}
		public FunctionConstructorExpContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionConstructorExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSubadditiveClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionSubadditiveClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSubadditiveClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionCompositionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionCompositionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionComposition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionRightExtContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionRightExtContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionRightExt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinPlusConvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinPlusConvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinPlusConvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarMultiplicationLeftContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionScalarMultiplicationLeftContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarMultiplicationLeft(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSubtractionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionSubtractionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSubtraction(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionVariableExpContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public FunctionVariableExpContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarDivisionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionScalarDivisionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarDivision(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionLeftExtContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionLeftExtContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionLeftExt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionExpressionContext functionExpression() {
		return functionExpression(0);
	}

	private FunctionExpressionContext functionExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		FunctionExpressionContext _localctx = new FunctionExpressionContext(Context, _parentState);
		FunctionExpressionContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_functionExpression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				{
				_localctx = new FunctionBracketsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 81;
				Match(T__1);
				State = 82;
				functionExpression(0);
				State = 83;
				Match(T__2);
				}
				break;
			case 2:
				{
				_localctx = new FunctionScalarMultiplicationRightContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 85;
				numberExpression(0);
				State = 86;
				Match(T__3);
				State = 87;
				functionExpression(9);
				}
				break;
			case 3:
				{
				_localctx = new FunctionConstructorExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 89;
				functionConstructor();
				}
				break;
			case 4:
				{
				_localctx = new FunctionSubadditiveClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 90;
				Match(T__12);
				State = 91;
				Match(T__1);
				State = 92;
				functionExpression(0);
				State = 93;
				Match(T__2);
				}
				break;
			case 5:
				{
				_localctx = new FunctionLeftExtContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 95;
				Match(T__13);
				State = 96;
				Match(T__1);
				State = 97;
				functionExpression(0);
				State = 98;
				Match(T__2);
				}
				break;
			case 6:
				{
				_localctx = new FunctionRightExtContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 100;
				Match(T__14);
				State = 101;
				Match(T__1);
				State = 102;
				functionExpression(0);
				State = 103;
				Match(T__2);
				}
				break;
			case 7:
				{
				_localctx = new FunctionVariableExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 105;
				Match(VARIABLE_NAME);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 137;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 135;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
					case 1:
						{
						_localctx = new FunctionMinPlusConvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 108;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 109;
						_la = TokenStream.LA(1);
						if ( !(_la==T__3 || _la==T__4) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 110;
						functionExpression(16);
						}
						break;
					case 2:
						{
						_localctx = new FunctionMaxPlusConvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 111;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 112;
						Match(T__5);
						State = 113;
						functionExpression(15);
						}
						break;
					case 3:
						{
						_localctx = new FunctionMinPlusDeconvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 114;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 115;
						_la = TokenStream.LA(1);
						if ( !(_la==T__6 || _la==T__7) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 116;
						functionExpression(14);
						}
						break;
					case 4:
						{
						_localctx = new FunctionMaxPlusDeconvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 117;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 118;
						Match(T__8);
						State = 119;
						functionExpression(13);
						}
						break;
					case 5:
						{
						_localctx = new FunctionCompositionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 120;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 121;
						Match(T__9);
						State = 122;
						functionExpression(12);
						}
						break;
					case 6:
						{
						_localctx = new FunctionSumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 123;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 124;
						Match(T__10);
						State = 125;
						functionExpression(8);
						}
						break;
					case 7:
						{
						_localctx = new FunctionSubtractionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 126;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 127;
						Match(T__11);
						State = 128;
						functionExpression(7);
						}
						break;
					case 8:
						{
						_localctx = new FunctionScalarMultiplicationLeftContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 129;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 130;
						Match(T__3);
						State = 131;
						numberExpression(0);
						}
						break;
					case 9:
						{
						_localctx = new FunctionScalarDivisionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 132;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 133;
						Match(T__6);
						State = 134;
						numberExpression(0);
						}
						break;
					}
					} 
				}
				State = 139;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FunctionConstructorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RateLatencyContext rateLatency() {
			return GetRuleContext<RateLatencyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TokenBucketContext tokenBucket() {
			return GetRuleContext<TokenBucketContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AffineFunctionContext affineFunction() {
			return GetRuleContext<AffineFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StairFunctionContext stairFunction() {
			return GetRuleContext<StairFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ZeroFunctionContext zeroFunction() {
			return GetRuleContext<ZeroFunctionContext>(0);
		}
		public FunctionConstructorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionConstructor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionConstructor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionConstructorContext functionConstructor() {
		FunctionConstructorContext _localctx = new FunctionConstructorContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionConstructor);
		try {
			State = 145;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__15:
				EnterOuterAlt(_localctx, 1);
				{
				State = 140;
				rateLatency();
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 2);
				{
				State = 141;
				tokenBucket();
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 3);
				{
				State = 142;
				affineFunction();
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 4);
				{
				State = 143;
				stairFunction();
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 5);
				{
				State = 144;
				zeroFunction();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RateLatencyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public RateLatencyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rateLatency; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRateLatency(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RateLatencyContext rateLatency() {
		RateLatencyContext _localctx = new RateLatencyContext(Context, State);
		EnterRule(_localctx, 14, RULE_rateLatency);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			Match(T__15);
			State = 148;
			Match(T__1);
			State = 149;
			numberExpression(0);
			State = 150;
			Match(T__16);
			State = 151;
			numberExpression(0);
			State = 152;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TokenBucketContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public TokenBucketContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tokenBucket; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTokenBucket(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TokenBucketContext tokenBucket() {
		TokenBucketContext _localctx = new TokenBucketContext(Context, State);
		EnterRule(_localctx, 16, RULE_tokenBucket);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 154;
			Match(T__17);
			State = 155;
			Match(T__1);
			State = 156;
			numberExpression(0);
			State = 157;
			Match(T__16);
			State = 158;
			numberExpression(0);
			State = 159;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AffineFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public AffineFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_affineFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAffineFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AffineFunctionContext affineFunction() {
		AffineFunctionContext _localctx = new AffineFunctionContext(Context, State);
		EnterRule(_localctx, 18, RULE_affineFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			Match(T__18);
			State = 162;
			Match(T__1);
			State = 163;
			numberExpression(0);
			State = 164;
			Match(T__16);
			State = 165;
			numberExpression(0);
			State = 166;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StairFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public StairFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stairFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStairFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StairFunctionContext stairFunction() {
		StairFunctionContext _localctx = new StairFunctionContext(Context, State);
		EnterRule(_localctx, 20, RULE_stairFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168;
			Match(T__19);
			State = 169;
			Match(T__1);
			State = 170;
			numberExpression(0);
			State = 171;
			Match(T__16);
			State = 172;
			numberExpression(0);
			State = 173;
			Match(T__16);
			State = 174;
			numberExpression(0);
			State = 175;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ZeroFunctionContext : ParserRuleContext {
		public ZeroFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_zeroFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitZeroFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ZeroFunctionContext zeroFunction() {
		ZeroFunctionContext _localctx = new ZeroFunctionContext(Context, State);
		EnterRule(_localctx, 22, RULE_zeroFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 177;
			Match(T__20);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberExpressionContext : ParserRuleContext {
		public NumberExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberExpression; } }
	 
		public NumberExpressionContext() { }
		public virtual void CopyFrom(NumberExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberReturningfunctionOperationExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberReturningfunctionOperationContext numberReturningfunctionOperation() {
			return GetRuleContext<NumberReturningfunctionOperationContext>(0);
		}
		public NumberReturningfunctionOperationExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberReturningfunctionOperationExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberBracketsContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public NumberBracketsContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberBrackets(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberVariableExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public NumberVariableExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberSumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberSumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberSum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMultiplicationContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMultiplicationContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMultiplication(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberLiteralExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(MppgParser.NUMBER_LITERAL, 0); }
		public NumberLiteralExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberLiteralExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberExpressionContext numberExpression() {
		return numberExpression(0);
	}

	private NumberExpressionContext numberExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		NumberExpressionContext _localctx = new NumberExpressionContext(Context, _parentState);
		NumberExpressionContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_numberExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__21:
			case T__22:
				{
				_localctx = new NumberReturningfunctionOperationExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 180;
				numberReturningfunctionOperation();
				}
				break;
			case T__1:
				{
				_localctx = new NumberBracketsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 181;
				Match(T__1);
				State = 182;
				numberExpression(0);
				State = 183;
				Match(T__2);
				}
				break;
			case VARIABLE_NAME:
				{
				_localctx = new NumberVariableExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 185;
				Match(VARIABLE_NAME);
				}
				break;
			case NUMBER_LITERAL:
				{
				_localctx = new NumberLiteralExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 186;
				Match(NUMBER_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 197;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 195;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
					case 1:
						{
						_localctx = new NumberMultiplicationContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 189;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 190;
						Match(T__3);
						State = 191;
						numberExpression(5);
						}
						break;
					case 2:
						{
						_localctx = new NumberSumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 192;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 193;
						Match(T__10);
						State = 194;
						numberExpression(4);
						}
						break;
					}
					} 
				}
				State = 199;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumberReturningfunctionOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionHorizontalDeviationContext functionHorizontalDeviation() {
			return GetRuleContext<FunctionHorizontalDeviationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionVerticalDeviationContext functionVerticalDeviation() {
			return GetRuleContext<FunctionVerticalDeviationContext>(0);
		}
		public NumberReturningfunctionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberReturningfunctionOperation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberReturningfunctionOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberReturningfunctionOperationContext numberReturningfunctionOperation() {
		NumberReturningfunctionOperationContext _localctx = new NumberReturningfunctionOperationContext(Context, State);
		EnterRule(_localctx, 26, RULE_numberReturningfunctionOperation);
		try {
			State = 202;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__21:
				EnterOuterAlt(_localctx, 1);
				{
				State = 200;
				functionHorizontalDeviation();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 2);
				{
				State = 201;
				functionVerticalDeviation();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionHorizontalDeviationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionHorizontalDeviationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionHorizontalDeviation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionHorizontalDeviation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionHorizontalDeviationContext functionHorizontalDeviation() {
		FunctionHorizontalDeviationContext _localctx = new FunctionHorizontalDeviationContext(Context, State);
		EnterRule(_localctx, 28, RULE_functionHorizontalDeviation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 204;
			Match(T__21);
			State = 205;
			Match(T__1);
			State = 206;
			functionExpression(0);
			State = 207;
			Match(T__16);
			State = 208;
			functionExpression(0);
			State = 209;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionVerticalDeviationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionVerticalDeviationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionVerticalDeviation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionVerticalDeviation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionVerticalDeviationContext functionVerticalDeviation() {
		FunctionVerticalDeviationContext _localctx = new FunctionVerticalDeviationContext(Context, State);
		EnterRule(_localctx, 30, RULE_functionVerticalDeviation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 211;
			Match(T__22);
			State = 212;
			Match(T__1);
			State = 213;
			functionExpression(0);
			State = 214;
			Match(T__16);
			State = 215;
			functionExpression(0);
			State = 216;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionsToPlotContext functionsToPlot() {
			return GetRuleContext<FunctionsToPlotContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgsContext plotArgs() {
			return GetRuleContext<PlotArgsContext>(0);
		}
		public PlotCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotCommandContext plotCommand() {
		PlotCommandContext _localctx = new PlotCommandContext(Context, State);
		EnterRule(_localctx, 32, RULE_plotCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 218;
			Match(T__23);
			State = 219;
			Match(T__1);
			State = 220;
			functionsToPlot();
			State = 223;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__16) {
				{
				State = 221;
				Match(T__16);
				State = 222;
				plotArgs();
				}
			}

			State = 225;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionsToPlotContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(MppgParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(MppgParser.VARIABLE_NAME, i);
		}
		public FunctionsToPlotContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionsToPlot; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionsToPlot(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionsToPlotContext functionsToPlot() {
		FunctionsToPlotContext _localctx = new FunctionsToPlotContext(Context, State);
		EnterRule(_localctx, 34, RULE_functionsToPlot);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			Match(VARIABLE_NAME);
			State = 232;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 228;
					Match(T__16);
					State = 229;
					Match(VARIABLE_NAME);
					}
					} 
				}
				State = 234;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgContext[] plotArg() {
			return GetRuleContexts<PlotArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgContext plotArg(int i) {
			return GetRuleContext<PlotArgContext>(i);
		}
		public PlotArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotArgsContext plotArgs() {
		PlotArgsContext _localctx = new PlotArgsContext(Context, State);
		EnterRule(_localctx, 36, RULE_plotArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 235;
			plotArg();
			State = 240;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__16) {
				{
				{
				State = 236;
				Match(T__16);
				State = 237;
				plotArg();
				}
				}
				State = 242;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IntervalContext interval() {
			return GetRuleContext<IntervalContext>(0);
		}
		public PlotArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotArgContext plotArg() {
		PlotArgContext _localctx = new PlotArgContext(Context, State);
		EnterRule(_localctx, 38, RULE_plotArg);
		try {
			State = 267;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__24:
				EnterOuterAlt(_localctx, 1);
				{
				State = 243;
				Match(T__24);
				State = 244;
				Match(T__25);
				State = 245;
				@string(0);
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 2);
				{
				State = 246;
				Match(T__26);
				State = 247;
				Match(T__25);
				State = 248;
				interval();
				}
				break;
			case T__27:
				EnterOuterAlt(_localctx, 3);
				{
				State = 249;
				Match(T__27);
				State = 250;
				Match(T__25);
				State = 251;
				interval();
				}
				break;
			case T__28:
				EnterOuterAlt(_localctx, 4);
				{
				State = 252;
				Match(T__28);
				State = 253;
				Match(T__25);
				State = 254;
				@string(0);
				}
				break;
			case T__29:
				EnterOuterAlt(_localctx, 5);
				{
				State = 255;
				Match(T__29);
				State = 256;
				Match(T__25);
				State = 257;
				@string(0);
				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 6);
				{
				State = 258;
				Match(T__30);
				State = 259;
				Match(T__25);
				State = 260;
				@string(0);
				}
				break;
			case T__31:
				EnterOuterAlt(_localctx, 7);
				{
				State = 261;
				Match(T__31);
				State = 262;
				Match(T__25);
				State = 263;
				Match(T__32);
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 8);
				{
				State = 264;
				Match(T__33);
				State = 265;
				Match(T__25);
				State = 266;
				Match(T__32);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(MppgParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(MppgParser.NUMBER_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		return @string(0);
	}

	private StringContext @string(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		StringContext _localctx = new StringContext(Context, _parentState);
		StringContext _prevctx = _localctx;
		int _startState = 40;
		EnterRecursionRule(_localctx, 40, RULE_string, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING_LITERAL:
				{
				State = 270;
				Match(STRING_LITERAL);
				}
				break;
			case VARIABLE_NAME:
				{
				State = 271;
				Match(VARIABLE_NAME);
				}
				break;
			case NUMBER_LITERAL:
				{
				State = 272;
				Match(NUMBER_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 280;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new StringContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_string);
					State = 275;
					if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
					State = 276;
					Match(T__10);
					State = 277;
					@string(5);
					}
					} 
				}
				State = 282;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class IntervalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER_LITERAL() { return GetTokens(MppgParser.NUMBER_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL(int i) {
			return GetToken(MppgParser.NUMBER_LITERAL, i);
		}
		public IntervalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interval; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterval(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntervalContext interval() {
		IntervalContext _localctx = new IntervalContext(Context, State);
		EnterRule(_localctx, 42, RULE_interval);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			Match(T__34);
			State = 284;
			Match(NUMBER_LITERAL);
			State = 285;
			Match(T__16);
			State = 286;
			Match(NUMBER_LITERAL);
			State = 287;
			Match(T__35);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintExpressionCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public PrintExpressionCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_printExpressionCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrintExpressionCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintExpressionCommandContext printExpressionCommand() {
		PrintExpressionCommandContext _localctx = new PrintExpressionCommandContext(Context, State);
		EnterRule(_localctx, 44, RULE_printExpressionCommand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 289;
			Match(T__36);
			State = 290;
			Match(T__1);
			State = 291;
			Match(VARIABLE_NAME);
			State = 292;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return functionExpression_sempred((FunctionExpressionContext)_localctx, predIndex);
		case 12: return numberExpression_sempred((NumberExpressionContext)_localctx, predIndex);
		case 20: return string_sempred((StringContext)_localctx, predIndex);
		}
		return true;
	}
	private bool functionExpression_sempred(FunctionExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		case 5: return Precpred(Context, 7);
		case 6: return Precpred(Context, 6);
		case 7: return Precpred(Context, 10);
		case 8: return Precpred(Context, 8);
		}
		return true;
	}
	private bool numberExpression_sempred(NumberExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 9: return Precpred(Context, 4);
		case 10: return Precpred(Context, 3);
		}
		return true;
	}
	private bool string_sempred(StringContext _localctx, int predIndex) {
		switch (predIndex) {
		case 11: return Precpred(Context, 4);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,46,295,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,1,0,1,0,1,0,5,0,50,8,0,10,0,12,0,53,9,0,1,0,3,0,56,8,0,1,0,1,
		0,1,1,1,1,1,1,1,1,1,1,3,1,65,8,1,1,2,1,2,1,2,1,2,1,3,1,3,3,3,73,8,3,1,
		4,1,4,4,4,77,8,4,11,4,12,4,78,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,107,
		8,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,5,5,136,8,5,10,5,12,5,139,9,
		5,1,6,1,6,1,6,1,6,1,6,3,6,146,8,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,8,1,8,
		1,8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,11,1,11,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,
		12,3,12,188,8,12,1,12,1,12,1,12,1,12,1,12,1,12,5,12,196,8,12,10,12,12,
		12,199,9,12,1,13,1,13,3,13,203,8,13,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,16,1,16,1,16,1,16,1,16,3,16,224,8,
		16,1,16,1,16,1,17,1,17,1,17,5,17,231,8,17,10,17,12,17,234,9,17,1,18,1,
		18,1,18,5,18,239,8,18,10,18,12,18,242,9,18,1,19,1,19,1,19,1,19,1,19,1,
		19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,
		19,1,19,1,19,1,19,1,19,3,19,268,8,19,1,20,1,20,1,20,1,20,3,20,274,8,20,
		1,20,1,20,1,20,5,20,279,8,20,10,20,12,20,282,9,20,1,21,1,21,1,21,1,21,
		1,21,1,21,1,22,1,22,1,22,1,22,1,22,1,22,0,3,10,24,40,23,0,2,4,6,8,10,12,
		14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,0,3,1,0,38,38,1,0,4,5,
		1,0,7,8,317,0,46,1,0,0,0,2,64,1,0,0,0,4,66,1,0,0,0,6,72,1,0,0,0,8,74,1,
		0,0,0,10,106,1,0,0,0,12,145,1,0,0,0,14,147,1,0,0,0,16,154,1,0,0,0,18,161,
		1,0,0,0,20,168,1,0,0,0,22,177,1,0,0,0,24,187,1,0,0,0,26,202,1,0,0,0,28,
		204,1,0,0,0,30,211,1,0,0,0,32,218,1,0,0,0,34,227,1,0,0,0,36,235,1,0,0,
		0,38,267,1,0,0,0,40,273,1,0,0,0,42,283,1,0,0,0,44,289,1,0,0,0,46,51,3,
		2,1,0,47,48,5,38,0,0,48,50,3,2,1,0,49,47,1,0,0,0,50,53,1,0,0,0,51,49,1,
		0,0,0,51,52,1,0,0,0,52,55,1,0,0,0,53,51,1,0,0,0,54,56,5,38,0,0,55,54,1,
		0,0,0,55,56,1,0,0,0,56,57,1,0,0,0,57,58,5,0,0,1,58,1,1,0,0,0,59,65,3,4,
		2,0,60,65,3,6,3,0,61,65,3,32,16,0,62,65,3,44,22,0,63,65,3,8,4,0,64,59,
		1,0,0,0,64,60,1,0,0,0,64,61,1,0,0,0,64,62,1,0,0,0,64,63,1,0,0,0,65,3,1,
		0,0,0,66,67,5,40,0,0,67,68,5,41,0,0,68,69,3,6,3,0,69,5,1,0,0,0,70,73,3,
		10,5,0,71,73,3,24,12,0,72,70,1,0,0,0,72,71,1,0,0,0,73,7,1,0,0,0,74,76,
		5,1,0,0,75,77,8,0,0,0,76,75,1,0,0,0,77,78,1,0,0,0,78,76,1,0,0,0,78,79,
		1,0,0,0,79,9,1,0,0,0,80,81,6,5,-1,0,81,82,5,2,0,0,82,83,3,10,5,0,83,84,
		5,3,0,0,84,107,1,0,0,0,85,86,3,24,12,0,86,87,5,4,0,0,87,88,3,10,5,9,88,
		107,1,0,0,0,89,107,3,12,6,0,90,91,5,13,0,0,91,92,5,2,0,0,92,93,3,10,5,
		0,93,94,5,3,0,0,94,107,1,0,0,0,95,96,5,14,0,0,96,97,5,2,0,0,97,98,3,10,
		5,0,98,99,5,3,0,0,99,107,1,0,0,0,100,101,5,15,0,0,101,102,5,2,0,0,102,
		103,3,10,5,0,103,104,5,3,0,0,104,107,1,0,0,0,105,107,5,40,0,0,106,80,1,
		0,0,0,106,85,1,0,0,0,106,89,1,0,0,0,106,90,1,0,0,0,106,95,1,0,0,0,106,
		100,1,0,0,0,106,105,1,0,0,0,107,137,1,0,0,0,108,109,10,15,0,0,109,110,
		7,1,0,0,110,136,3,10,5,16,111,112,10,14,0,0,112,113,5,6,0,0,113,136,3,
		10,5,15,114,115,10,13,0,0,115,116,7,2,0,0,116,136,3,10,5,14,117,118,10,
		12,0,0,118,119,5,9,0,0,119,136,3,10,5,13,120,121,10,11,0,0,121,122,5,10,
		0,0,122,136,3,10,5,12,123,124,10,7,0,0,124,125,5,11,0,0,125,136,3,10,5,
		8,126,127,10,6,0,0,127,128,5,12,0,0,128,136,3,10,5,7,129,130,10,10,0,0,
		130,131,5,4,0,0,131,136,3,24,12,0,132,133,10,8,0,0,133,134,5,7,0,0,134,
		136,3,24,12,0,135,108,1,0,0,0,135,111,1,0,0,0,135,114,1,0,0,0,135,117,
		1,0,0,0,135,120,1,0,0,0,135,123,1,0,0,0,135,126,1,0,0,0,135,129,1,0,0,
		0,135,132,1,0,0,0,136,139,1,0,0,0,137,135,1,0,0,0,137,138,1,0,0,0,138,
		11,1,0,0,0,139,137,1,0,0,0,140,146,3,14,7,0,141,146,3,16,8,0,142,146,3,
		18,9,0,143,146,3,20,10,0,144,146,3,22,11,0,145,140,1,0,0,0,145,141,1,0,
		0,0,145,142,1,0,0,0,145,143,1,0,0,0,145,144,1,0,0,0,146,13,1,0,0,0,147,
		148,5,16,0,0,148,149,5,2,0,0,149,150,3,24,12,0,150,151,5,17,0,0,151,152,
		3,24,12,0,152,153,5,3,0,0,153,15,1,0,0,0,154,155,5,18,0,0,155,156,5,2,
		0,0,156,157,3,24,12,0,157,158,5,17,0,0,158,159,3,24,12,0,159,160,5,3,0,
		0,160,17,1,0,0,0,161,162,5,19,0,0,162,163,5,2,0,0,163,164,3,24,12,0,164,
		165,5,17,0,0,165,166,3,24,12,0,166,167,5,3,0,0,167,19,1,0,0,0,168,169,
		5,20,0,0,169,170,5,2,0,0,170,171,3,24,12,0,171,172,5,17,0,0,172,173,3,
		24,12,0,173,174,5,17,0,0,174,175,3,24,12,0,175,176,5,3,0,0,176,21,1,0,
		0,0,177,178,5,21,0,0,178,23,1,0,0,0,179,180,6,12,-1,0,180,188,3,26,13,
		0,181,182,5,2,0,0,182,183,3,24,12,0,183,184,5,3,0,0,184,188,1,0,0,0,185,
		188,5,40,0,0,186,188,5,43,0,0,187,179,1,0,0,0,187,181,1,0,0,0,187,185,
		1,0,0,0,187,186,1,0,0,0,188,197,1,0,0,0,189,190,10,4,0,0,190,191,5,4,0,
		0,191,196,3,24,12,5,192,193,10,3,0,0,193,194,5,11,0,0,194,196,3,24,12,
		4,195,189,1,0,0,0,195,192,1,0,0,0,196,199,1,0,0,0,197,195,1,0,0,0,197,
		198,1,0,0,0,198,25,1,0,0,0,199,197,1,0,0,0,200,203,3,28,14,0,201,203,3,
		30,15,0,202,200,1,0,0,0,202,201,1,0,0,0,203,27,1,0,0,0,204,205,5,22,0,
		0,205,206,5,2,0,0,206,207,3,10,5,0,207,208,5,17,0,0,208,209,3,10,5,0,209,
		210,5,3,0,0,210,29,1,0,0,0,211,212,5,23,0,0,212,213,5,2,0,0,213,214,3,
		10,5,0,214,215,5,17,0,0,215,216,3,10,5,0,216,217,5,3,0,0,217,31,1,0,0,
		0,218,219,5,24,0,0,219,220,5,2,0,0,220,223,3,34,17,0,221,222,5,17,0,0,
		222,224,3,36,18,0,223,221,1,0,0,0,223,224,1,0,0,0,224,225,1,0,0,0,225,
		226,5,3,0,0,226,33,1,0,0,0,227,232,5,40,0,0,228,229,5,17,0,0,229,231,5,
		40,0,0,230,228,1,0,0,0,231,234,1,0,0,0,232,230,1,0,0,0,232,233,1,0,0,0,
		233,35,1,0,0,0,234,232,1,0,0,0,235,240,3,38,19,0,236,237,5,17,0,0,237,
		239,3,38,19,0,238,236,1,0,0,0,239,242,1,0,0,0,240,238,1,0,0,0,240,241,
		1,0,0,0,241,37,1,0,0,0,242,240,1,0,0,0,243,244,5,25,0,0,244,245,5,26,0,
		0,245,268,3,40,20,0,246,247,5,27,0,0,247,248,5,26,0,0,248,268,3,42,21,
		0,249,250,5,28,0,0,250,251,5,26,0,0,251,268,3,42,21,0,252,253,5,29,0,0,
		253,254,5,26,0,0,254,268,3,40,20,0,255,256,5,30,0,0,256,257,5,26,0,0,257,
		268,3,40,20,0,258,259,5,31,0,0,259,260,5,26,0,0,260,268,3,40,20,0,261,
		262,5,32,0,0,262,263,5,26,0,0,263,268,5,33,0,0,264,265,5,34,0,0,265,266,
		5,26,0,0,266,268,5,33,0,0,267,243,1,0,0,0,267,246,1,0,0,0,267,249,1,0,
		0,0,267,252,1,0,0,0,267,255,1,0,0,0,267,258,1,0,0,0,267,261,1,0,0,0,267,
		264,1,0,0,0,268,39,1,0,0,0,269,270,6,20,-1,0,270,274,5,42,0,0,271,274,
		5,40,0,0,272,274,5,43,0,0,273,269,1,0,0,0,273,271,1,0,0,0,273,272,1,0,
		0,0,274,280,1,0,0,0,275,276,10,4,0,0,276,277,5,11,0,0,277,279,3,40,20,
		5,278,275,1,0,0,0,279,282,1,0,0,0,280,278,1,0,0,0,280,281,1,0,0,0,281,
		41,1,0,0,0,282,280,1,0,0,0,283,284,5,35,0,0,284,285,5,43,0,0,285,286,5,
		17,0,0,286,287,5,43,0,0,287,288,5,36,0,0,288,43,1,0,0,0,289,290,5,37,0,
		0,290,291,5,2,0,0,291,292,5,40,0,0,292,293,5,3,0,0,293,45,1,0,0,0,19,51,
		55,64,72,78,106,135,137,145,187,195,197,202,223,232,240,267,273,280
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Unipi.MppgParser.Grammar
