//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Mppg.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Unipi.MppgParser.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class MppgParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, NEW_LINE=42, WHITE_SPACE=43, VARIABLE_NAME=44, 
		ASSIGN=45, STRING_LITERAL=46, COMMENT=47, NUMBER_LITERAL=48, RATIONAL_NUMBER_LITERAL=49, 
		DECIMAL_NUMBER_LITERAL=50, INFINITE_NUMBER_LITERAL=51;
	public const int
		RULE_program = 0, RULE_statement = 1, RULE_assignment = 2, RULE_expression = 3, 
		RULE_comment = 4, RULE_functionExpression = 5, RULE_functionConstructor = 6, 
		RULE_rateLatency = 7, RULE_tokenBucket = 8, RULE_affineFunction = 9, RULE_stairFunction = 10, 
		RULE_delayFunction = 11, RULE_zeroFunction = 12, RULE_numberExpression = 13, 
		RULE_numberReturningfunctionOperation = 14, RULE_functionHorizontalDeviation = 15, 
		RULE_functionVerticalDeviation = 16, RULE_plotCommand = 17, RULE_functionsToPlot = 18, 
		RULE_functionName = 19, RULE_plotArgs = 20, RULE_plotArg = 21, RULE_string = 22, 
		RULE_interval = 23, RULE_printExpressionCommand = 24;
	public static readonly string[] ruleNames = {
		"program", "statement", "assignment", "expression", "comment", "functionExpression", 
		"functionConstructor", "rateLatency", "tokenBucket", "affineFunction", 
		"stairFunction", "delayFunction", "zeroFunction", "numberExpression", 
		"numberReturningfunctionOperation", "functionHorizontalDeviation", "functionVerticalDeviation", 
		"plotCommand", "functionsToPlot", "functionName", "plotArgs", "plotArg", 
		"string", "interval", "printExpressionCommand"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'/\\'", "'\\/'", "'*'", "'*_'", "'*^'", "'/'", "'/_'", 
		"'/^'", "'comp'", "'+'", "'-'", "'star'", "'upclosure'", "'nnupclosure'", 
		"'left-ext'", "'right-ext'", "'ratency'", "','", "'bucket'", "'affine'", 
		"'stair'", "'delay'", "'zero'", "'hDev'", "'vDev'", "'plot'", "'main'", 
		"'='", "'xlim'", "'ylim'", "'xlab'", "'ylab'", "'out'", "'grid'", "'\"no\"'", 
		"'bg'", "'['", "']'", "'printExpression'", null, null, null, "':='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "NEW_LINE", "WHITE_SPACE", "VARIABLE_NAME", 
		"ASSIGN", "STRING_LITERAL", "COMMENT", "NUMBER_LITERAL", "RATIONAL_NUMBER_LITERAL", 
		"DECIMAL_NUMBER_LITERAL", "INFINITE_NUMBER_LITERAL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Mppg.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MppgParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MppgParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MppgParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MppgParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEW_LINE() { return GetTokens(MppgParser.NEW_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW_LINE(int i) {
			return GetToken(MppgParser.NEW_LINE, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			statement();
			State = 55;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 51;
					Match(NEW_LINE);
					State = 52;
					statement();
					}
					} 
				}
				State = 57;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NEW_LINE) {
				{
				State = 58;
				Match(NEW_LINE);
				}
			}

			State = 61;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotCommandContext plotCommand() {
			return GetRuleContext<PlotCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintExpressionCommandContext printExpressionCommand() {
			return GetRuleContext<PrintExpressionCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommentContext comment() {
			return GetRuleContext<CommentContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			State = 68;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 63;
				assignment();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64;
				expression();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 65;
				plotCommand();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 66;
				printExpressionCommand();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 67;
				comment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MppgParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 4, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(VARIABLE_NAME);
			State = 71;
			Match(ASSIGN);
			State = 72;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_expression);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 74;
				functionExpression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 75;
				numberExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(MppgParser.COMMENT, 0); }
		public CommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommentContext comment() {
		CommentContext _localctx = new CommentContext(Context, State);
		EnterRule(_localctx, 8, RULE_comment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionExpressionContext : ParserRuleContext {
		public FunctionExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionExpression; } }
	 
		public FunctionExpressionContext() { }
		public virtual void CopyFrom(FunctionExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FunctionMaximumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionMaximumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaximum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMaxPlusDeconvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaxPlusDeconvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaxPlusDeconvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMaxPlusConvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMaxPlusConvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMaxPlusConvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionSumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionBracketsContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionBracketsContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionBrackets(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarMultiplicationRightContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionScalarMultiplicationRightContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarMultiplicationRight(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinPlusDeconvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinPlusDeconvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinPlusDeconvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionUpNonDecreasingClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionUpNonDecreasingClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionUpNonDecreasingClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSubadditiveClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionSubadditiveClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSubadditiveClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionConstructorExpContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionConstructorContext functionConstructor() {
			return GetRuleContext<FunctionConstructorContext>(0);
		}
		public FunctionConstructorExpContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionConstructorExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionCompositionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionCompositionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionComposition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinimumContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionMinimumContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinimum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionRightExtContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionRightExtContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionRightExt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionMinPlusConvolutionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionMinPlusConvolutionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionMinPlusConvolution(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarMultiplicationLeftContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionScalarMultiplicationLeftContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarMultiplicationLeft(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionSubtractionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionSubtractionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSubtraction(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionNonNegativeUpNonDecreasingClosureContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionNonNegativeUpNonDecreasingClosureContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionNonNegativeUpNonDecreasingClosure(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionVariableExpContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public FunctionVariableExpContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionScalarDivisionContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public FunctionScalarDivisionContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionScalarDivision(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionLeftExtContext : FunctionExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression() {
			return GetRuleContext<FunctionExpressionContext>(0);
		}
		public FunctionLeftExtContext(FunctionExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionLeftExt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionExpressionContext functionExpression() {
		return functionExpression(0);
	}

	private FunctionExpressionContext functionExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		FunctionExpressionContext _localctx = new FunctionExpressionContext(Context, _parentState);
		FunctionExpressionContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_functionExpression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				_localctx = new FunctionBracketsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 81;
				Match(T__0);
				State = 82;
				functionExpression(0);
				State = 83;
				Match(T__1);
				}
				break;
			case 2:
				{
				_localctx = new FunctionScalarMultiplicationRightContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 85;
				numberExpression(0);
				State = 86;
				Match(T__4);
				State = 87;
				functionExpression(11);
				}
				break;
			case 3:
				{
				_localctx = new FunctionSubadditiveClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 89;
				Match(T__13);
				State = 90;
				Match(T__0);
				State = 91;
				functionExpression(0);
				State = 92;
				Match(T__1);
				}
				break;
			case 4:
				{
				_localctx = new FunctionUpNonDecreasingClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 94;
				Match(T__14);
				State = 95;
				Match(T__0);
				State = 96;
				functionExpression(0);
				State = 97;
				Match(T__1);
				}
				break;
			case 5:
				{
				_localctx = new FunctionNonNegativeUpNonDecreasingClosureContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 99;
				Match(T__15);
				State = 100;
				Match(T__0);
				State = 101;
				functionExpression(0);
				State = 102;
				Match(T__1);
				}
				break;
			case 6:
				{
				_localctx = new FunctionLeftExtContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 104;
				Match(T__16);
				State = 105;
				Match(T__0);
				State = 106;
				functionExpression(0);
				State = 107;
				Match(T__1);
				}
				break;
			case 7:
				{
				_localctx = new FunctionRightExtContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 109;
				Match(T__17);
				State = 110;
				Match(T__0);
				State = 111;
				functionExpression(0);
				State = 112;
				Match(T__1);
				}
				break;
			case 8:
				{
				_localctx = new FunctionConstructorExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 114;
				functionConstructor();
				}
				break;
			case 9:
				{
				_localctx = new FunctionVariableExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 115;
				Match(VARIABLE_NAME);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 159;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 157;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
					case 1:
						{
						_localctx = new FunctionMinimumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 118;
						if (!(Precpred(Context, 21))) throw new FailedPredicateException(this, "Precpred(Context, 21)");
						State = 119;
						Match(T__2);
						State = 120;
						functionExpression(22);
						}
						break;
					case 2:
						{
						_localctx = new FunctionMaximumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 121;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 122;
						Match(T__3);
						State = 123;
						functionExpression(20);
						}
						break;
					case 3:
						{
						_localctx = new FunctionMinPlusConvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 124;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 125;
						_la = TokenStream.LA(1);
						if ( !(_la==T__4 || _la==T__5) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 126;
						functionExpression(18);
						}
						break;
					case 4:
						{
						_localctx = new FunctionMaxPlusConvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 127;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 128;
						Match(T__6);
						State = 129;
						functionExpression(17);
						}
						break;
					case 5:
						{
						_localctx = new FunctionMinPlusDeconvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 130;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 131;
						_la = TokenStream.LA(1);
						if ( !(_la==T__7 || _la==T__8) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 132;
						functionExpression(16);
						}
						break;
					case 6:
						{
						_localctx = new FunctionMaxPlusDeconvolutionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 133;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 134;
						Match(T__9);
						State = 135;
						functionExpression(15);
						}
						break;
					case 7:
						{
						_localctx = new FunctionCompositionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 136;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 137;
						Match(T__10);
						State = 138;
						functionExpression(14);
						}
						break;
					case 8:
						{
						_localctx = new FunctionSumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 139;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 140;
						Match(T__11);
						State = 141;
						functionExpression(10);
						}
						break;
					case 9:
						{
						_localctx = new FunctionSubtractionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 142;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 143;
						Match(T__12);
						State = 144;
						functionExpression(9);
						}
						break;
					case 10:
						{
						_localctx = new FunctionMinimumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 145;
						if (!(Precpred(Context, 20))) throw new FailedPredicateException(this, "Precpred(Context, 20)");
						State = 146;
						Match(T__2);
						State = 147;
						numberExpression(0);
						}
						break;
					case 11:
						{
						_localctx = new FunctionMaximumContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 148;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 149;
						Match(T__3);
						State = 150;
						numberExpression(0);
						}
						break;
					case 12:
						{
						_localctx = new FunctionScalarMultiplicationLeftContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 151;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 152;
						Match(T__4);
						State = 153;
						numberExpression(0);
						}
						break;
					case 13:
						{
						_localctx = new FunctionScalarDivisionContext(new FunctionExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_functionExpression);
						State = 154;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 155;
						Match(T__7);
						State = 156;
						numberExpression(0);
						}
						break;
					}
					} 
				}
				State = 161;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FunctionConstructorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RateLatencyContext rateLatency() {
			return GetRuleContext<RateLatencyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TokenBucketContext tokenBucket() {
			return GetRuleContext<TokenBucketContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AffineFunctionContext affineFunction() {
			return GetRuleContext<AffineFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StairFunctionContext stairFunction() {
			return GetRuleContext<StairFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DelayFunctionContext delayFunction() {
			return GetRuleContext<DelayFunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ZeroFunctionContext zeroFunction() {
			return GetRuleContext<ZeroFunctionContext>(0);
		}
		public FunctionConstructorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionConstructor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionConstructor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionConstructorContext functionConstructor() {
		FunctionConstructorContext _localctx = new FunctionConstructorContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionConstructor);
		try {
			State = 168;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
				EnterOuterAlt(_localctx, 1);
				{
				State = 162;
				rateLatency();
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 2);
				{
				State = 163;
				tokenBucket();
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 3);
				{
				State = 164;
				affineFunction();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 4);
				{
				State = 165;
				stairFunction();
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 5);
				{
				State = 166;
				delayFunction();
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 6);
				{
				State = 167;
				zeroFunction();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RateLatencyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public RateLatencyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rateLatency; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRateLatency(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RateLatencyContext rateLatency() {
		RateLatencyContext _localctx = new RateLatencyContext(Context, State);
		EnterRule(_localctx, 14, RULE_rateLatency);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170;
			Match(T__18);
			State = 171;
			Match(T__0);
			State = 172;
			numberExpression(0);
			State = 173;
			Match(T__19);
			State = 174;
			numberExpression(0);
			State = 175;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TokenBucketContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public TokenBucketContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tokenBucket; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTokenBucket(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TokenBucketContext tokenBucket() {
		TokenBucketContext _localctx = new TokenBucketContext(Context, State);
		EnterRule(_localctx, 16, RULE_tokenBucket);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 177;
			Match(T__20);
			State = 178;
			Match(T__0);
			State = 179;
			numberExpression(0);
			State = 180;
			Match(T__19);
			State = 181;
			numberExpression(0);
			State = 182;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AffineFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public AffineFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_affineFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAffineFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AffineFunctionContext affineFunction() {
		AffineFunctionContext _localctx = new AffineFunctionContext(Context, State);
		EnterRule(_localctx, 18, RULE_affineFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(T__21);
			State = 185;
			Match(T__0);
			State = 186;
			numberExpression(0);
			State = 187;
			Match(T__19);
			State = 188;
			numberExpression(0);
			State = 189;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StairFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public StairFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stairFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStairFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StairFunctionContext stairFunction() {
		StairFunctionContext _localctx = new StairFunctionContext(Context, State);
		EnterRule(_localctx, 20, RULE_stairFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			Match(T__22);
			State = 192;
			Match(T__0);
			State = 193;
			numberExpression(0);
			State = 194;
			Match(T__19);
			State = 195;
			numberExpression(0);
			State = 196;
			Match(T__19);
			State = 197;
			numberExpression(0);
			State = 198;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DelayFunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public DelayFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_delayFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDelayFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DelayFunctionContext delayFunction() {
		DelayFunctionContext _localctx = new DelayFunctionContext(Context, State);
		EnterRule(_localctx, 22, RULE_delayFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			Match(T__23);
			State = 201;
			Match(T__0);
			State = 202;
			numberExpression(0);
			State = 203;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ZeroFunctionContext : ParserRuleContext {
		public ZeroFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_zeroFunction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitZeroFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ZeroFunctionContext zeroFunction() {
		ZeroFunctionContext _localctx = new ZeroFunctionContext(Context, State);
		EnterRule(_localctx, 24, RULE_zeroFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 205;
			Match(T__24);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberExpressionContext : ParserRuleContext {
		public NumberExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberExpression; } }
	 
		public NumberExpressionContext() { }
		public virtual void CopyFrom(NumberExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NumberSubContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberSubContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberSub(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberReturningfunctionOperationExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberReturningfunctionOperationContext numberReturningfunctionOperation() {
			return GetRuleContext<NumberReturningfunctionOperationContext>(0);
		}
		public NumberReturningfunctionOperationExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberReturningfunctionOperationExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberBracketsContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression() {
			return GetRuleContext<NumberExpressionContext>(0);
		}
		public NumberBracketsContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberBrackets(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberVariableExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public NumberVariableExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberVariableExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberSumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberSumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberSum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMaximumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMaximumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMaximum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMinimumContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMinimumContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMinimum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberMultiplicationContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberMultiplicationContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberMultiplication(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberLiteralExpContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(MppgParser.NUMBER_LITERAL, 0); }
		public NumberLiteralExpContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberLiteralExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberDivisionContext : NumberExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext[] numberExpression() {
			return GetRuleContexts<NumberExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberExpressionContext numberExpression(int i) {
			return GetRuleContext<NumberExpressionContext>(i);
		}
		public NumberDivisionContext(NumberExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberDivision(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberExpressionContext numberExpression() {
		return numberExpression(0);
	}

	private NumberExpressionContext numberExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		NumberExpressionContext _localctx = new NumberExpressionContext(Context, _parentState);
		NumberExpressionContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_numberExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 215;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
			case T__26:
				{
				_localctx = new NumberReturningfunctionOperationExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 208;
				numberReturningfunctionOperation();
				}
				break;
			case T__0:
				{
				_localctx = new NumberBracketsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 209;
				Match(T__0);
				State = 210;
				numberExpression(0);
				State = 211;
				Match(T__1);
				}
				break;
			case VARIABLE_NAME:
				{
				_localctx = new NumberVariableExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 213;
				Match(VARIABLE_NAME);
				}
				break;
			case NUMBER_LITERAL:
				{
				_localctx = new NumberLiteralExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 214;
				Match(NUMBER_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 237;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 235;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
					case 1:
						{
						_localctx = new NumberMultiplicationContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 217;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 218;
						Match(T__4);
						State = 219;
						numberExpression(9);
						}
						break;
					case 2:
						{
						_localctx = new NumberDivisionContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 220;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 221;
						Match(T__7);
						State = 222;
						numberExpression(8);
						}
						break;
					case 3:
						{
						_localctx = new NumberSumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 223;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 224;
						Match(T__11);
						State = 225;
						numberExpression(7);
						}
						break;
					case 4:
						{
						_localctx = new NumberSubContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 226;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 227;
						Match(T__12);
						State = 228;
						numberExpression(6);
						}
						break;
					case 5:
						{
						_localctx = new NumberMinimumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 229;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 230;
						Match(T__2);
						State = 231;
						numberExpression(5);
						}
						break;
					case 6:
						{
						_localctx = new NumberMaximumContext(new NumberExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_numberExpression);
						State = 232;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 233;
						Match(T__3);
						State = 234;
						numberExpression(4);
						}
						break;
					}
					} 
				}
				State = 239;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumberReturningfunctionOperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionHorizontalDeviationContext functionHorizontalDeviation() {
			return GetRuleContext<FunctionHorizontalDeviationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionVerticalDeviationContext functionVerticalDeviation() {
			return GetRuleContext<FunctionVerticalDeviationContext>(0);
		}
		public NumberReturningfunctionOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberReturningfunctionOperation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberReturningfunctionOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberReturningfunctionOperationContext numberReturningfunctionOperation() {
		NumberReturningfunctionOperationContext _localctx = new NumberReturningfunctionOperationContext(Context, State);
		EnterRule(_localctx, 28, RULE_numberReturningfunctionOperation);
		try {
			State = 242;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__25:
				EnterOuterAlt(_localctx, 1);
				{
				State = 240;
				functionHorizontalDeviation();
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 2);
				{
				State = 241;
				functionVerticalDeviation();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionHorizontalDeviationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionHorizontalDeviationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionHorizontalDeviation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionHorizontalDeviation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionHorizontalDeviationContext functionHorizontalDeviation() {
		FunctionHorizontalDeviationContext _localctx = new FunctionHorizontalDeviationContext(Context, State);
		EnterRule(_localctx, 30, RULE_functionHorizontalDeviation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 244;
			Match(T__25);
			State = 245;
			Match(T__0);
			State = 246;
			functionExpression(0);
			State = 247;
			Match(T__19);
			State = 248;
			functionExpression(0);
			State = 249;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionVerticalDeviationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext[] functionExpression() {
			return GetRuleContexts<FunctionExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionExpressionContext functionExpression(int i) {
			return GetRuleContext<FunctionExpressionContext>(i);
		}
		public FunctionVerticalDeviationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionVerticalDeviation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionVerticalDeviation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionVerticalDeviationContext functionVerticalDeviation() {
		FunctionVerticalDeviationContext _localctx = new FunctionVerticalDeviationContext(Context, State);
		EnterRule(_localctx, 32, RULE_functionVerticalDeviation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 251;
			Match(T__26);
			State = 252;
			Match(T__0);
			State = 253;
			functionExpression(0);
			State = 254;
			Match(T__19);
			State = 255;
			functionExpression(0);
			State = 256;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionsToPlotContext functionsToPlot() {
			return GetRuleContext<FunctionsToPlotContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgsContext plotArgs() {
			return GetRuleContext<PlotArgsContext>(0);
		}
		public PlotCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotCommandContext plotCommand() {
		PlotCommandContext _localctx = new PlotCommandContext(Context, State);
		EnterRule(_localctx, 34, RULE_plotCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 258;
			Match(T__27);
			State = 259;
			Match(T__0);
			State = 260;
			functionsToPlot();
			State = 263;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__19) {
				{
				State = 261;
				Match(T__19);
				State = 262;
				plotArgs();
				}
			}

			State = 265;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionsToPlotContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionNameContext[] functionName() {
			return GetRuleContexts<FunctionNameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionNameContext functionName(int i) {
			return GetRuleContext<FunctionNameContext>(i);
		}
		public FunctionsToPlotContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionsToPlot; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionsToPlot(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionsToPlotContext functionsToPlot() {
		FunctionsToPlotContext _localctx = new FunctionsToPlotContext(Context, State);
		EnterRule(_localctx, 36, RULE_functionsToPlot);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 267;
			functionName();
			State = 272;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 268;
					Match(T__19);
					State = 269;
					functionName();
					}
					} 
				}
				State = 274;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public FunctionNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionNameContext functionName() {
		FunctionNameContext _localctx = new FunctionNameContext(Context, State);
		EnterRule(_localctx, 38, RULE_functionName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 275;
			Match(VARIABLE_NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgContext[] plotArg() {
			return GetRuleContexts<PlotArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PlotArgContext plotArg(int i) {
			return GetRuleContext<PlotArgContext>(i);
		}
		public PlotArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotArgsContext plotArgs() {
		PlotArgsContext _localctx = new PlotArgsContext(Context, State);
		EnterRule(_localctx, 40, RULE_plotArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 277;
			plotArg();
			State = 282;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__19) {
				{
				{
				State = 278;
				Match(T__19);
				State = 279;
				plotArg();
				}
				}
				State = 284;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PlotArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IntervalContext interval() {
			return GetRuleContext<IntervalContext>(0);
		}
		public PlotArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plotArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlotArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PlotArgContext plotArg() {
		PlotArgContext _localctx = new PlotArgContext(Context, State);
		EnterRule(_localctx, 42, RULE_plotArg);
		try {
			State = 309;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__28:
				EnterOuterAlt(_localctx, 1);
				{
				State = 285;
				Match(T__28);
				State = 286;
				Match(T__29);
				State = 287;
				@string(0);
				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 2);
				{
				State = 288;
				Match(T__30);
				State = 289;
				Match(T__29);
				State = 290;
				interval();
				}
				break;
			case T__31:
				EnterOuterAlt(_localctx, 3);
				{
				State = 291;
				Match(T__31);
				State = 292;
				Match(T__29);
				State = 293;
				interval();
				}
				break;
			case T__32:
				EnterOuterAlt(_localctx, 4);
				{
				State = 294;
				Match(T__32);
				State = 295;
				Match(T__29);
				State = 296;
				@string(0);
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 5);
				{
				State = 297;
				Match(T__33);
				State = 298;
				Match(T__29);
				State = 299;
				@string(0);
				}
				break;
			case T__34:
				EnterOuterAlt(_localctx, 6);
				{
				State = 300;
				Match(T__34);
				State = 301;
				Match(T__29);
				State = 302;
				@string(0);
				}
				break;
			case T__35:
				EnterOuterAlt(_localctx, 7);
				{
				State = 303;
				Match(T__35);
				State = 304;
				Match(T__29);
				State = 305;
				Match(T__36);
				}
				break;
			case T__37:
				EnterOuterAlt(_localctx, 8);
				{
				State = 306;
				Match(T__37);
				State = 307;
				Match(T__29);
				State = 308;
				Match(T__36);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(MppgParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL() { return GetToken(MppgParser.NUMBER_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StringContext[] @string() {
			return GetRuleContexts<StringContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string(int i) {
			return GetRuleContext<StringContext>(i);
		}
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		return @string(0);
	}

	private StringContext @string(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		StringContext _localctx = new StringContext(Context, _parentState);
		StringContext _prevctx = _localctx;
		int _startState = 44;
		EnterRecursionRule(_localctx, 44, RULE_string, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 315;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING_LITERAL:
				{
				State = 312;
				Match(STRING_LITERAL);
				}
				break;
			case VARIABLE_NAME:
				{
				State = 313;
				Match(VARIABLE_NAME);
				}
				break;
			case NUMBER_LITERAL:
				{
				State = 314;
				Match(NUMBER_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 322;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new StringContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_string);
					State = 317;
					if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
					State = 318;
					Match(T__11);
					State = 319;
					@string(5);
					}
					} 
				}
				State = 324;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class IntervalContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER_LITERAL() { return GetTokens(MppgParser.NUMBER_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER_LITERAL(int i) {
			return GetToken(MppgParser.NUMBER_LITERAL, i);
		}
		public IntervalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interval; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterval(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntervalContext interval() {
		IntervalContext _localctx = new IntervalContext(Context, State);
		EnterRule(_localctx, 46, RULE_interval);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 325;
			Match(T__38);
			State = 326;
			Match(NUMBER_LITERAL);
			State = 327;
			Match(T__19);
			State = 328;
			Match(NUMBER_LITERAL);
			State = 329;
			Match(T__39);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintExpressionCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(MppgParser.VARIABLE_NAME, 0); }
		public PrintExpressionCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_printExpressionCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMppgVisitor<TResult> typedVisitor = visitor as IMppgVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrintExpressionCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintExpressionCommandContext printExpressionCommand() {
		PrintExpressionCommandContext _localctx = new PrintExpressionCommandContext(Context, State);
		EnterRule(_localctx, 48, RULE_printExpressionCommand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 331;
			Match(T__40);
			State = 332;
			Match(T__0);
			State = 333;
			Match(VARIABLE_NAME);
			State = 334;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return functionExpression_sempred((FunctionExpressionContext)_localctx, predIndex);
		case 13: return numberExpression_sempred((NumberExpressionContext)_localctx, predIndex);
		case 22: return string_sempred((StringContext)_localctx, predIndex);
		}
		return true;
	}
	private bool functionExpression_sempred(FunctionExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 21);
		case 1: return Precpred(Context, 19);
		case 2: return Precpred(Context, 17);
		case 3: return Precpred(Context, 16);
		case 4: return Precpred(Context, 15);
		case 5: return Precpred(Context, 14);
		case 6: return Precpred(Context, 13);
		case 7: return Precpred(Context, 9);
		case 8: return Precpred(Context, 8);
		case 9: return Precpred(Context, 20);
		case 10: return Precpred(Context, 18);
		case 11: return Precpred(Context, 12);
		case 12: return Precpred(Context, 10);
		}
		return true;
	}
	private bool numberExpression_sempred(NumberExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 13: return Precpred(Context, 8);
		case 14: return Precpred(Context, 7);
		case 15: return Precpred(Context, 6);
		case 16: return Precpred(Context, 5);
		case 17: return Precpred(Context, 4);
		case 18: return Precpred(Context, 3);
		}
		return true;
	}
	private bool string_sempred(StringContext _localctx, int predIndex) {
		switch (predIndex) {
		case 19: return Precpred(Context, 4);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,51,337,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,1,0,1,0,1,0,5,0,54,8,0,10,0,12,0,57,9,0,
		1,0,3,0,60,8,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,3,1,69,8,1,1,2,1,2,1,2,1,2,
		1,3,1,3,3,3,77,8,3,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,117,8,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,5,5,158,8,5,
		10,5,12,5,161,9,5,1,6,1,6,1,6,1,6,1,6,1,6,3,6,169,8,6,1,7,1,7,1,7,1,7,
		1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,1,11,1,
		12,1,12,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,3,13,216,8,13,1,13,1,13,
		1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,
		1,13,1,13,5,13,236,8,13,10,13,12,13,239,9,13,1,14,1,14,3,14,243,8,14,1,
		15,1,15,1,15,1,15,1,15,1,15,1,15,1,16,1,16,1,16,1,16,1,16,1,16,1,16,1,
		17,1,17,1,17,1,17,1,17,3,17,264,8,17,1,17,1,17,1,18,1,18,1,18,5,18,271,
		8,18,10,18,12,18,274,9,18,1,19,1,19,1,20,1,20,1,20,5,20,281,8,20,10,20,
		12,20,284,9,20,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,
		1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,3,21,
		310,8,21,1,22,1,22,1,22,1,22,3,22,316,8,22,1,22,1,22,1,22,5,22,321,8,22,
		10,22,12,22,324,9,22,1,23,1,23,1,23,1,23,1,23,1,23,1,24,1,24,1,24,1,24,
		1,24,1,24,0,3,10,26,44,25,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,
		34,36,38,40,42,44,46,48,0,2,1,0,5,6,1,0,8,9,367,0,50,1,0,0,0,2,68,1,0,
		0,0,4,70,1,0,0,0,6,76,1,0,0,0,8,78,1,0,0,0,10,116,1,0,0,0,12,168,1,0,0,
		0,14,170,1,0,0,0,16,177,1,0,0,0,18,184,1,0,0,0,20,191,1,0,0,0,22,200,1,
		0,0,0,24,205,1,0,0,0,26,215,1,0,0,0,28,242,1,0,0,0,30,244,1,0,0,0,32,251,
		1,0,0,0,34,258,1,0,0,0,36,267,1,0,0,0,38,275,1,0,0,0,40,277,1,0,0,0,42,
		309,1,0,0,0,44,315,1,0,0,0,46,325,1,0,0,0,48,331,1,0,0,0,50,55,3,2,1,0,
		51,52,5,42,0,0,52,54,3,2,1,0,53,51,1,0,0,0,54,57,1,0,0,0,55,53,1,0,0,0,
		55,56,1,0,0,0,56,59,1,0,0,0,57,55,1,0,0,0,58,60,5,42,0,0,59,58,1,0,0,0,
		59,60,1,0,0,0,60,61,1,0,0,0,61,62,5,0,0,1,62,1,1,0,0,0,63,69,3,4,2,0,64,
		69,3,6,3,0,65,69,3,34,17,0,66,69,3,48,24,0,67,69,3,8,4,0,68,63,1,0,0,0,
		68,64,1,0,0,0,68,65,1,0,0,0,68,66,1,0,0,0,68,67,1,0,0,0,69,3,1,0,0,0,70,
		71,5,44,0,0,71,72,5,45,0,0,72,73,3,6,3,0,73,5,1,0,0,0,74,77,3,10,5,0,75,
		77,3,26,13,0,76,74,1,0,0,0,76,75,1,0,0,0,77,7,1,0,0,0,78,79,5,47,0,0,79,
		9,1,0,0,0,80,81,6,5,-1,0,81,82,5,1,0,0,82,83,3,10,5,0,83,84,5,2,0,0,84,
		117,1,0,0,0,85,86,3,26,13,0,86,87,5,5,0,0,87,88,3,10,5,11,88,117,1,0,0,
		0,89,90,5,14,0,0,90,91,5,1,0,0,91,92,3,10,5,0,92,93,5,2,0,0,93,117,1,0,
		0,0,94,95,5,15,0,0,95,96,5,1,0,0,96,97,3,10,5,0,97,98,5,2,0,0,98,117,1,
		0,0,0,99,100,5,16,0,0,100,101,5,1,0,0,101,102,3,10,5,0,102,103,5,2,0,0,
		103,117,1,0,0,0,104,105,5,17,0,0,105,106,5,1,0,0,106,107,3,10,5,0,107,
		108,5,2,0,0,108,117,1,0,0,0,109,110,5,18,0,0,110,111,5,1,0,0,111,112,3,
		10,5,0,112,113,5,2,0,0,113,117,1,0,0,0,114,117,3,12,6,0,115,117,5,44,0,
		0,116,80,1,0,0,0,116,85,1,0,0,0,116,89,1,0,0,0,116,94,1,0,0,0,116,99,1,
		0,0,0,116,104,1,0,0,0,116,109,1,0,0,0,116,114,1,0,0,0,116,115,1,0,0,0,
		117,159,1,0,0,0,118,119,10,21,0,0,119,120,5,3,0,0,120,158,3,10,5,22,121,
		122,10,19,0,0,122,123,5,4,0,0,123,158,3,10,5,20,124,125,10,17,0,0,125,
		126,7,0,0,0,126,158,3,10,5,18,127,128,10,16,0,0,128,129,5,7,0,0,129,158,
		3,10,5,17,130,131,10,15,0,0,131,132,7,1,0,0,132,158,3,10,5,16,133,134,
		10,14,0,0,134,135,5,10,0,0,135,158,3,10,5,15,136,137,10,13,0,0,137,138,
		5,11,0,0,138,158,3,10,5,14,139,140,10,9,0,0,140,141,5,12,0,0,141,158,3,
		10,5,10,142,143,10,8,0,0,143,144,5,13,0,0,144,158,3,10,5,9,145,146,10,
		20,0,0,146,147,5,3,0,0,147,158,3,26,13,0,148,149,10,18,0,0,149,150,5,4,
		0,0,150,158,3,26,13,0,151,152,10,12,0,0,152,153,5,5,0,0,153,158,3,26,13,
		0,154,155,10,10,0,0,155,156,5,8,0,0,156,158,3,26,13,0,157,118,1,0,0,0,
		157,121,1,0,0,0,157,124,1,0,0,0,157,127,1,0,0,0,157,130,1,0,0,0,157,133,
		1,0,0,0,157,136,1,0,0,0,157,139,1,0,0,0,157,142,1,0,0,0,157,145,1,0,0,
		0,157,148,1,0,0,0,157,151,1,0,0,0,157,154,1,0,0,0,158,161,1,0,0,0,159,
		157,1,0,0,0,159,160,1,0,0,0,160,11,1,0,0,0,161,159,1,0,0,0,162,169,3,14,
		7,0,163,169,3,16,8,0,164,169,3,18,9,0,165,169,3,20,10,0,166,169,3,22,11,
		0,167,169,3,24,12,0,168,162,1,0,0,0,168,163,1,0,0,0,168,164,1,0,0,0,168,
		165,1,0,0,0,168,166,1,0,0,0,168,167,1,0,0,0,169,13,1,0,0,0,170,171,5,19,
		0,0,171,172,5,1,0,0,172,173,3,26,13,0,173,174,5,20,0,0,174,175,3,26,13,
		0,175,176,5,2,0,0,176,15,1,0,0,0,177,178,5,21,0,0,178,179,5,1,0,0,179,
		180,3,26,13,0,180,181,5,20,0,0,181,182,3,26,13,0,182,183,5,2,0,0,183,17,
		1,0,0,0,184,185,5,22,0,0,185,186,5,1,0,0,186,187,3,26,13,0,187,188,5,20,
		0,0,188,189,3,26,13,0,189,190,5,2,0,0,190,19,1,0,0,0,191,192,5,23,0,0,
		192,193,5,1,0,0,193,194,3,26,13,0,194,195,5,20,0,0,195,196,3,26,13,0,196,
		197,5,20,0,0,197,198,3,26,13,0,198,199,5,2,0,0,199,21,1,0,0,0,200,201,
		5,24,0,0,201,202,5,1,0,0,202,203,3,26,13,0,203,204,5,2,0,0,204,23,1,0,
		0,0,205,206,5,25,0,0,206,25,1,0,0,0,207,208,6,13,-1,0,208,216,3,28,14,
		0,209,210,5,1,0,0,210,211,3,26,13,0,211,212,5,2,0,0,212,216,1,0,0,0,213,
		216,5,44,0,0,214,216,5,48,0,0,215,207,1,0,0,0,215,209,1,0,0,0,215,213,
		1,0,0,0,215,214,1,0,0,0,216,237,1,0,0,0,217,218,10,8,0,0,218,219,5,5,0,
		0,219,236,3,26,13,9,220,221,10,7,0,0,221,222,5,8,0,0,222,236,3,26,13,8,
		223,224,10,6,0,0,224,225,5,12,0,0,225,236,3,26,13,7,226,227,10,5,0,0,227,
		228,5,13,0,0,228,236,3,26,13,6,229,230,10,4,0,0,230,231,5,3,0,0,231,236,
		3,26,13,5,232,233,10,3,0,0,233,234,5,4,0,0,234,236,3,26,13,4,235,217,1,
		0,0,0,235,220,1,0,0,0,235,223,1,0,0,0,235,226,1,0,0,0,235,229,1,0,0,0,
		235,232,1,0,0,0,236,239,1,0,0,0,237,235,1,0,0,0,237,238,1,0,0,0,238,27,
		1,0,0,0,239,237,1,0,0,0,240,243,3,30,15,0,241,243,3,32,16,0,242,240,1,
		0,0,0,242,241,1,0,0,0,243,29,1,0,0,0,244,245,5,26,0,0,245,246,5,1,0,0,
		246,247,3,10,5,0,247,248,5,20,0,0,248,249,3,10,5,0,249,250,5,2,0,0,250,
		31,1,0,0,0,251,252,5,27,0,0,252,253,5,1,0,0,253,254,3,10,5,0,254,255,5,
		20,0,0,255,256,3,10,5,0,256,257,5,2,0,0,257,33,1,0,0,0,258,259,5,28,0,
		0,259,260,5,1,0,0,260,263,3,36,18,0,261,262,5,20,0,0,262,264,3,40,20,0,
		263,261,1,0,0,0,263,264,1,0,0,0,264,265,1,0,0,0,265,266,5,2,0,0,266,35,
		1,0,0,0,267,272,3,38,19,0,268,269,5,20,0,0,269,271,3,38,19,0,270,268,1,
		0,0,0,271,274,1,0,0,0,272,270,1,0,0,0,272,273,1,0,0,0,273,37,1,0,0,0,274,
		272,1,0,0,0,275,276,5,44,0,0,276,39,1,0,0,0,277,282,3,42,21,0,278,279,
		5,20,0,0,279,281,3,42,21,0,280,278,1,0,0,0,281,284,1,0,0,0,282,280,1,0,
		0,0,282,283,1,0,0,0,283,41,1,0,0,0,284,282,1,0,0,0,285,286,5,29,0,0,286,
		287,5,30,0,0,287,310,3,44,22,0,288,289,5,31,0,0,289,290,5,30,0,0,290,310,
		3,46,23,0,291,292,5,32,0,0,292,293,5,30,0,0,293,310,3,46,23,0,294,295,
		5,33,0,0,295,296,5,30,0,0,296,310,3,44,22,0,297,298,5,34,0,0,298,299,5,
		30,0,0,299,310,3,44,22,0,300,301,5,35,0,0,301,302,5,30,0,0,302,310,3,44,
		22,0,303,304,5,36,0,0,304,305,5,30,0,0,305,310,5,37,0,0,306,307,5,38,0,
		0,307,308,5,30,0,0,308,310,5,37,0,0,309,285,1,0,0,0,309,288,1,0,0,0,309,
		291,1,0,0,0,309,294,1,0,0,0,309,297,1,0,0,0,309,300,1,0,0,0,309,303,1,
		0,0,0,309,306,1,0,0,0,310,43,1,0,0,0,311,312,6,22,-1,0,312,316,5,46,0,
		0,313,316,5,44,0,0,314,316,5,48,0,0,315,311,1,0,0,0,315,313,1,0,0,0,315,
		314,1,0,0,0,316,322,1,0,0,0,317,318,10,4,0,0,318,319,5,12,0,0,319,321,
		3,44,22,5,320,317,1,0,0,0,321,324,1,0,0,0,322,320,1,0,0,0,322,323,1,0,
		0,0,323,45,1,0,0,0,324,322,1,0,0,0,325,326,5,39,0,0,326,327,5,48,0,0,327,
		328,5,20,0,0,328,329,5,48,0,0,329,330,5,40,0,0,330,47,1,0,0,0,331,332,
		5,41,0,0,332,333,5,1,0,0,333,334,5,44,0,0,334,335,5,2,0,0,335,49,1,0,0,
		0,18,55,59,68,76,116,157,159,168,215,235,237,242,263,272,282,309,315,322
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Unipi.MppgParser.Grammar
