//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Mppg.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Unipi.MppgParser.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MppgParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMppgVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MppgParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.preamble"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreamble([NotNull] MppgParser.PreambleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.preambleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreambleStatement([NotNull] MppgParser.PreambleStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.versionDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersionDirective([NotNull] MppgParser.VersionDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirective([NotNull] MppgParser.DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.statementLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementLine([NotNull] MppgParser.StatementLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MppgParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] MppgParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.expressionCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionCommand([NotNull] MppgParser.ExpressionCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MppgParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] MppgParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.inlineComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineComment([NotNull] MppgParser.InlineCommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty([NotNull] MppgParser.EmptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExpression([NotNull] MppgParser.FunctionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSumChain</c>
	/// labeled alternative in <see cref="MppgParser.functionSumExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSumChain([NotNull] MppgParser.FunctionSumChainContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSumFunctionStart</c>
	/// labeled alternative in <see cref="MppgParser.functionSumStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSumFunctionStart([NotNull] MppgParser.FunctionSumFunctionStartContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionShiftMinMaxRev</c>
	/// labeled alternative in <see cref="MppgParser.functionSumStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionShiftMinMaxRev([NotNull] MppgParser.FunctionShiftMinMaxRevContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSumSubMinMaxSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionSumSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSumSubMinMaxSuffix([NotNull] MppgParser.FunctionSumSubMinMaxSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionShiftMinMaxSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionSumSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionShiftMinMaxSuffix([NotNull] MppgParser.FunctionShiftMinMaxSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionProductChain</c>
	/// labeled alternative in <see cref="MppgParser.functionProductExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionProductChain([NotNull] MppgParser.FunctionProductChainContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionProductFunctionStart</c>
	/// labeled alternative in <see cref="MppgParser.functionProductStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionProductFunctionStart([NotNull] MppgParser.FunctionProductFunctionStartContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarMulRev</c>
	/// labeled alternative in <see cref="MppgParser.functionProductStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarMulRev([NotNull] MppgParser.FunctionScalarMulRevContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarCompositionRev</c>
	/// labeled alternative in <see cref="MppgParser.functionProductStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarCompositionRev([NotNull] MppgParser.FunctionScalarCompositionRevContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMinPlusConvolutionSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMinPlusConvolutionSuffix([NotNull] MppgParser.FunctionMinPlusConvolutionSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarMulSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarMulSuffix([NotNull] MppgParser.FunctionScalarMulSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMaxPlusConvolutionSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMaxPlusConvolutionSuffix([NotNull] MppgParser.FunctionMaxPlusConvolutionSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMinPlusDeconvolutionSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMinPlusDeconvolutionSuffix([NotNull] MppgParser.FunctionMinPlusDeconvolutionSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarDivSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarDivSuffix([NotNull] MppgParser.FunctionScalarDivSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionMaxPlusDeconvolutionSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionMaxPlusDeconvolutionSuffix([NotNull] MppgParser.FunctionMaxPlusDeconvolutionSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionComposition</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionComposition([NotNull] MppgParser.FunctionCompositionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionScalarCompositionSuffix</c>
	/// labeled alternative in <see cref="MppgParser.functionProductSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScalarCompositionSuffix([NotNull] MppgParser.FunctionScalarCompositionSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionPositive</c>
	/// labeled alternative in <see cref="MppgParser.functionUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionPositive([NotNull] MppgParser.FunctionPositiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionNegative</c>
	/// labeled alternative in <see cref="MppgParser.functionUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionNegative([NotNull] MppgParser.FunctionNegativeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionEnclosedExpressionExp</c>
	/// labeled alternative in <see cref="MppgParser.functionUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionEnclosedExpressionExp([NotNull] MppgParser.FunctionEnclosedExpressionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionBrackets</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBrackets([NotNull] MppgParser.FunctionBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSubadditiveClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSubadditiveClosure([NotNull] MppgParser.FunctionSubadditiveClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionSuperadditiveClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSuperadditiveClosure([NotNull] MppgParser.FunctionSuperadditiveClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionHShift</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionHShift([NotNull] MppgParser.FunctionHShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionVShift</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVShift([NotNull] MppgParser.FunctionVShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionLowerPseudoInverse</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionLowerPseudoInverse([NotNull] MppgParser.FunctionLowerPseudoInverseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionUpperPseudoInverse</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionUpperPseudoInverse([NotNull] MppgParser.FunctionUpperPseudoInverseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionUpNonDecreasingClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionUpNonDecreasingClosure([NotNull] MppgParser.FunctionUpNonDecreasingClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionNonNegativeUpNonDecreasingClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionNonNegativeUpNonDecreasingClosure([NotNull] MppgParser.FunctionNonNegativeUpNonDecreasingClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionLowNonDecreasingClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionLowNonDecreasingClosure([NotNull] MppgParser.FunctionLowNonDecreasingClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionNonNegativeLowNonDecreasingClosure</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionNonNegativeLowNonDecreasingClosure([NotNull] MppgParser.FunctionNonNegativeLowNonDecreasingClosureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionLeftExt</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionLeftExt([NotNull] MppgParser.FunctionLeftExtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionRightExt</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionRightExt([NotNull] MppgParser.FunctionRightExtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionFloor</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionFloor([NotNull] MppgParser.FunctionFloorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionCeil</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCeil([NotNull] MppgParser.FunctionCeilContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionConstructorExp</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionConstructorExp([NotNull] MppgParser.FunctionConstructorExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionVariableExp</c>
	/// labeled alternative in <see cref="MppgParser.functionEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVariableExp([NotNull] MppgParser.FunctionVariableExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionConstructor([NotNull] MppgParser.FunctionConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.rateLatency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRateLatency([NotNull] MppgParser.RateLatencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.tokenBucket"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokenBucket([NotNull] MppgParser.TokenBucketContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.affineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAffineFunction([NotNull] MppgParser.AffineFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.stepFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStepFunction([NotNull] MppgParser.StepFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.stairFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStairFunction([NotNull] MppgParser.StairFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.delayFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelayFunction([NotNull] MppgParser.DelayFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.zeroFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZeroFunction([NotNull] MppgParser.ZeroFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.epsilonFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEpsilonFunction([NotNull] MppgParser.EpsilonFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.ultimatelyAffineFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUltimatelyAffineFunction([NotNull] MppgParser.UltimatelyAffineFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.ultimatelyPseudoPeriodicFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUltimatelyPseudoPeriodicFunction([NotNull] MppgParser.UltimatelyPseudoPeriodicFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.uppTransientPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUppTransientPart([NotNull] MppgParser.UppTransientPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.uppPeriodicPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUppPeriodicPart([NotNull] MppgParser.UppPeriodicPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncrement([NotNull] MppgParser.IncrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.periodLenght"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPeriodLenght([NotNull] MppgParser.PeriodLenghtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequence([NotNull] MppgParser.SequenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] MppgParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPoint([NotNull] MppgParser.PointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegment([NotNull] MppgParser.SegmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.endpoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpoint([NotNull] MppgParser.EndpointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.segmentLeftOpenRightOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegmentLeftOpenRightOpen([NotNull] MppgParser.SegmentLeftOpenRightOpenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.segmentLeftOpenRightClosed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegmentLeftOpenRightClosed([NotNull] MppgParser.SegmentLeftOpenRightClosedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.segmentLeftClosedRightOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegmentLeftClosedRightOpen([NotNull] MppgParser.SegmentLeftClosedRightOpenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.segmentLeftClosedRightClosed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegmentLeftClosedRightClosed([NotNull] MppgParser.SegmentLeftClosedRightClosedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberReturningfunctionOperationExp</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberReturningfunctionOperationExp([NotNull] MppgParser.NumberReturningfunctionOperationExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberMulDiv</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberMulDiv([NotNull] MppgParser.NumberMulDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberBrackets</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberBrackets([NotNull] MppgParser.NumberBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberVariableExp</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberVariableExp([NotNull] MppgParser.NumberVariableExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberGcd</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberGcd([NotNull] MppgParser.NumberGcdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberNegative</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberNegative([NotNull] MppgParser.NumberNegativeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberMod</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberMod([NotNull] MppgParser.NumberModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberSumSubMinMax</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberSumSubMinMax([NotNull] MppgParser.NumberSumSubMinMaxContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberFloor</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberFloor([NotNull] MppgParser.NumberFloorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberCeil</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberCeil([NotNull] MppgParser.NumberCeilContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberPow</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberPow([NotNull] MppgParser.NumberPowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberLcm</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLcm([NotNull] MppgParser.NumberLcmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberPositive</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberPositive([NotNull] MppgParser.NumberPositiveContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberAbs</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberAbs([NotNull] MppgParser.NumberAbsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberLiteralExp</c>
	/// labeled alternative in <see cref="MppgParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteralExp([NotNull] MppgParser.NumberLiteralExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberReturningfunctionOperationExp</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberReturningfunctionOperationExp([NotNull] MppgParser.EncNumberReturningfunctionOperationExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberFloor</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberFloor([NotNull] MppgParser.EncNumberFloorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberCeil</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberCeil([NotNull] MppgParser.EncNumberCeilContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberAbs</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberAbs([NotNull] MppgParser.EncNumberAbsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberPow</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberPow([NotNull] MppgParser.EncNumberPowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberMod</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberMod([NotNull] MppgParser.EncNumberModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberGcd</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberGcd([NotNull] MppgParser.EncNumberGcdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberLcm</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberLcm([NotNull] MppgParser.EncNumberLcmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberBrackets</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberBrackets([NotNull] MppgParser.EncNumberBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberVariableExp</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberVariableExp([NotNull] MppgParser.EncNumberVariableExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>encNumberLiteralExp</c>
	/// labeled alternative in <see cref="MppgParser.numberEnclosedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncNumberLiteralExp([NotNull] MppgParser.EncNumberLiteralExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.numberLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteral([NotNull] MppgParser.NumberLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.numberReturningfunctionOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberReturningfunctionOperation([NotNull] MppgParser.NumberReturningfunctionOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionValueAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionValueAt([NotNull] MppgParser.FunctionValueAtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionLeftLimitAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionLeftLimitAt([NotNull] MppgParser.FunctionLeftLimitAtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionRightLimitAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionRightLimitAt([NotNull] MppgParser.FunctionRightLimitAtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionHorizontalDeviation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionHorizontalDeviation([NotNull] MppgParser.FunctionHorizontalDeviationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionVerticalDeviation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVerticalDeviation([NotNull] MppgParser.FunctionVerticalDeviationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionZDeviation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionZDeviation([NotNull] MppgParser.FunctionZDeviationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotCommand([NotNull] MppgParser.PlotCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotTikzCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotTikzCommand([NotNull] MppgParser.PlotTikzCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotArg([NotNull] MppgParser.PlotArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] MppgParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.plotOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlotOption([NotNull] MppgParser.PlotOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] MppgParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] MppgParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.stringVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringVariable([NotNull] MppgParser.StringVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterval([NotNull] MppgParser.IntervalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.assertion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertion([NotNull] MppgParser.AssertionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.assertionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertionOperator([NotNull] MppgParser.AssertionOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MppgParser.printExpressionCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintExpressionCommand([NotNull] MppgParser.PrintExpressionCommandContext context);
}
} // namespace Unipi.MppgParser.Grammar
